"""Our content ids <-> app archetypes, and entity construction.

Every lookup the AI makes goes from one of our ids (card instance id, space
id, conflict id, contract id, leader id, post id, faction id) to the app
archetype whose attributes and abilities the app AI would read. The tables
are explicit (no fuzzy matching at runtime) and tests check that every id our
4-player Uprising content can deal maps to an archetype that is dealt in the
app's game with the same CHOAM setting, and that the Immortality, Epic Game
Mode and promo content maps to the app's archetypes of the same cards
(``ARCHETYPES`` holds every archetype the app defines).

Content the app does not have (Bloodlines with its Tech Module and the promo
Ruthless Leadership, Arrakeen Scouts) gets synthetic archetypes built by the
app-data rules of ``docs/app-ai-plan.md`` §11.3 (``data/synthetic.py``,
generated by ``scripts/dwgr/app_ai_synth.py``; short names
``<Kind>Archetypes.AppStyle.<Name>``). The same tables map our ids to them;
``archetype`` looks a short name up in the app extraction first, then in the
synthetic set. New entity kinds: Tech tiles (``tech_entity``), the Sardaukar
Commander and its Skills (``commander_entity``, ``skill_entity``),
Navigation cards (``navigation_entity``) and Scouts lines
(``scouts_line_entity``).

Board overlays (``space_entity``; all off without their option, so games
without Bloodlines or Scouts keep the app's archetypes as they are):
- ``Board.bloodlines``: ``AS.AcquireCommanderAbility`` on the six Commander
  spaces (bloodlines-systems.md §6);
- ``Board.tech_module``: the Rise of Ix ``AcquireTechAbility`` on the five
  Landsraad spaces (§6, the Ixian Embassy);
- ``Board.scouts``: ``MissionPiecesSpaceAbility`` on every space, the
  ``SubcommitteeOfferAbility`` on High Council, ``DesertRidingAbility`` in
  place of Hagga Basin's deferred ability (scouts.md §4.1, §4.2, §4.5, §4.8);
- ``Board.faction_spaces_combat`` (Eyes on Arrakis this round): the five
  Faction spaces that are not Combat spaces become Combat spaces with the
  app's ``DeployUnitsAbility`` (scouts.md §4.7).

Tuek's Sietch (Esmar Tuek's own space) has a synthetic archetype but stays out
of ``SPACE_ARCHETYPES``, which the profile reads as "every space of the
board": ``BLOODLINES_SPACE_ARCHETYPES`` holds it, ``space_entity`` resolves it,
and ``BLOODLINES_SPACE_ORDER`` is its place after the app's spaces.

Known content differences (``scratchpad R5`` / ``spec/archetypes.md``):
- The app's reserve holds Foldspace x6; our engine has no Foldspace.
- Our three Uprising promos and Piter, Genius Advisor are ``Promo``
  archetypes the app never deals; app_ai values them with those archetypes.
- Accept Contract, Dutiful Service, CHOAM Security and Trade Dispute have an
  ``...UP`` archetype (no CHOAM) and a ``...CHOAM`` one; pick by ``choam``.
"""

from functools import cache
from types import MappingProxyType
from typing import Final

from dune_imperium.agents.app_ai.context import Board, card_id
from dune_imperium.agents.app_ai.data.archetypes import ARCHETYPES, Archetype
from dune_imperium.agents.app_ai.data.synthetic import SCOUTS_LINES, SYNTHETIC
from dune_imperium.agents.app_ai.entities import Entity, Kind


def _both(short: str) -> tuple[str, str]:
    """An archetype that is the same with and without the CHOAM module."""

    return (short, short)


# card_id -> app archetype short name (starters, reserve, Imperium incl. CHOAM
# and promos).
CARD_ARCHETYPES: dict[str, str] = {
    # Starting deck (BaseSet starters).
    "convincing_argument": "ImperiumArchetypes.BaseSet.ConvincingArgument",
    "dagger": "ImperiumArchetypes.BaseSet.Dagger",
    "diplomacy": "ImperiumArchetypes.BaseSet.Diplomacy",
    "dune_the_desert_planet": "ImperiumArchetypes.BaseSet.DunetheDesertPlanet",
    "reconnaissance": "ImperiumArchetypes.BaseSet.Reconnaissance",
    "seek_allies": "ImperiumArchetypes.BaseSet.SeekAllies",
    "signet_ring": "ImperiumArchetypes.BaseSet.SignetRing",
    # Reserve stacks.
    "prepare_the_way": "ImperiumArchetypes.Uprising.PreparetheWay",
    "the_spice_must_flow": "ImperiumArchetypes.Uprising.TheSpiceMustFlowUP",
    # Imperium deck: base cards and the four CHOAM-only cards.
    "bene_gesserit_operative": "ImperiumArchetypes.Uprising.BeneGesseritOperative",
    "branching_path": "ImperiumArchetypes.Uprising.BranchingPath",
    "calculus_of_power": "ImperiumArchetypes.Uprising.CalculusofPower",
    "captured_mentat": "ImperiumArchetypes.Uprising.CapturedMentat",
    "cargo_runner": "ImperiumArchetypes.Uprising.CargoRunner",
    "chani_clever_tactician": "ImperiumArchetypes.Uprising.ChaniCleverTactician",
    "corrinth_city": "ImperiumArchetypes.Uprising.CorrinthCity",
    "covert_operation": "ImperiumArchetypes.Uprising.CovertOperation",
    "dangerous_rhetoric": "ImperiumArchetypes.Uprising.DangerousRhetoric",
    "delivery_agreement": "ImperiumArchetypes.Uprising.DeliveryAgreement",
    "desert_power": "ImperiumArchetypes.Uprising.DesertPowerImperium",
    "desert_survival": "ImperiumArchetypes.Uprising.DesertSurvival",
    "double_agent": "ImperiumArchetypes.Uprising.DoubleAgent",
    "ecological_testing_station": (
        "ImperiumArchetypes.Uprising.EcologicalTestingStation"
    ),
    "fedaykin_stilltent": "ImperiumArchetypes.Uprising.FedaykinStilltent",
    "guild_envoy": "ImperiumArchetypes.Uprising.GuildEnvoy",
    "guild_spy": "ImperiumArchetypes.Uprising.GuildSpy",
    "hidden_missive": "ImperiumArchetypes.Uprising.HiddenMissive",
    "imperial_spymaster": "ImperiumArchetypes.Uprising.ImperialSpymaster",
    "in_high_places": "ImperiumArchetypes.Uprising.InHighPlaces",
    "interstellar_trade": "ImperiumArchetypes.Uprising.InterstellarTrade",
    "junction_headquarters": "ImperiumArchetypes.Uprising.JunctionHeadquarters",
    "leadership": "ImperiumArchetypes.Uprising.Leadership",
    "long_live_the_fighters": "ImperiumArchetypes.Uprising.LongLivetheFighters",
    "maker_keeper": "ImperiumArchetypes.Uprising.MakerKeeper",
    "maula_pistol": "ImperiumArchetypes.Uprising.MaulaPistol",
    "northern_watermaster": "ImperiumArchetypes.Uprising.NorthernWatermaster",
    "overthrow": "ImperiumArchetypes.Uprising.Overthrow",
    "paracompass": "ImperiumArchetypes.Uprising.Paracompass",
    "price_is_no_object": "ImperiumArchetypes.Uprising.PriceisNoObject",
    "priority_contracts": "ImperiumArchetypes.Uprising.PriorityContracts",
    "public_spectacle": "ImperiumArchetypes.Uprising.PublicSpectacle",
    "rebel_supplier": "ImperiumArchetypes.Uprising.RebelSupplier",
    "reliable_informant": "ImperiumArchetypes.Uprising.ReliableInformant",
    "sardaukar_coordination": "ImperiumArchetypes.Uprising.SardaukarCoordination",
    "sardaukar_soldier": "ImperiumArchetypes.Uprising.SardaukarSoldier",
    "shishakli": "ImperiumArchetypes.Uprising.Shishakli",
    "smuggler_s_harvester": "ImperiumArchetypes.Uprising.SmugglersHarvester",
    "smuggler_s_haven": "ImperiumArchetypes.Uprising.SmugglersHaven",
    "southern_elders": "ImperiumArchetypes.Uprising.SouthernElders",
    "space_time_folding": "ImperiumArchetypes.Uprising.SpacetimeFolding",
    "spacing_guild_s_favor": "ImperiumArchetypes.Uprising.SpacingGuildsFavor",
    "spy_network": "ImperiumArchetypes.Uprising.SpyNetwork",
    "steersman": "ImperiumArchetypes.Uprising.Steersman",
    "stilgar_the_devoted": "ImperiumArchetypes.Uprising.StilgartheDevoted",
    "strike_fleet": "ImperiumArchetypes.Uprising.StrikeFleet",
    "subversive_advisor": "ImperiumArchetypes.Uprising.SubversiveAdvisor",
    "treacherous_maneuver": "ImperiumArchetypes.Uprising.TreacherousManeuver",
    "tread_in_darkness": "ImperiumArchetypes.Uprising.TreadinDarkness",
    "truthtrance": "ImperiumArchetypes.Uprising.Truthtrance",
    "undercover_asset": "ImperiumArchetypes.Uprising.UndercoverAsset",
    "unswerving_loyalty": "ImperiumArchetypes.Uprising.UnswervingLoyalty",
    "weirding_woman": "ImperiumArchetypes.Uprising.WeirdingWoman",
    "wheels_within_wheels": "ImperiumArchetypes.Uprising.WheelsWithinWheels",
    # Uprising promos. The app deals none of them (``ImperiumType = Promo``);
    # they map to the app's own archetypes of the same cards.
    "arrakis_revolt": "ImperiumArchetypes.Promo.ArrakisRevolt",
    "pivotal_gambit": "ImperiumArchetypes.Promo.PivotalGambit",
    "the_beast_s_spoils": "ImperiumArchetypes.Promo.TheBeastsSpoils",
    # Immortality: the starter that replaces Dune, the Desert Planet, and the
    # 25 Imperium kinds (``imperium_cards_for_choam(..., immortality=True)``).
    "experimentation": "ImperiumArchetypes.Immortality.Experimentation",
    "bene_tleilax_lab": "ImperiumArchetypes.Immortality.BeneTleilaxLab",
    "bene_tleilax_researcher": "ImperiumArchetypes.Immortality.BeneTleilaxResearcher",
    "blank_slate": "ImperiumArchetypes.Immortality.BlankSlate",
    "clandestine_meeting": "ImperiumArchetypes.Immortality.ClandestineMeeting",
    "corrupt_smuggler": "ImperiumArchetypes.Immortality.CorruptSmuggler",
    "dissecting_kit": "ImperiumArchetypes.Immortality.DissectingKit",
    "for_humanity": "ImperiumArchetypes.Immortality.ForHumanity",
    "high_priority_travel": "ImperiumArchetypes.Immortality.HighPriorityTravel",
    "imperium_ceremony": "ImperiumArchetypes.Immortality.ImperiumCeremony",
    "interstellar_conspiracy": "ImperiumArchetypes.Immortality.InterstellarConspiracy",
    "keys_to_power": "ImperiumArchetypes.Immortality.KeystoPower",
    "lisan_al_gaib": "ImperiumArchetypes.Immortality.LisanalGaib",
    "long_reach": "ImperiumArchetypes.Immortality.LongReach",
    "occupation": "ImperiumArchetypes.Immortality.Occupation",
    "organ_merchants": "ImperiumArchetypes.Immortality.OrganMerchants",
    "planned_coupling": "ImperiumArchetypes.Immortality.PlannedCoupling",
    "replacement_eyes": "ImperiumArchetypes.Immortality.ReplacementEyes",
    "sardaukar_quartermaster": "ImperiumArchetypes.Immortality.SardaukarQuartermaster",
    "shadout_mapes": "ImperiumArchetypes.Immortality.ShadoutMapes",
    "show_of_strength": "ImperiumArchetypes.Immortality.ShowofStrength",
    "spiritual_fervor": "ImperiumArchetypes.Immortality.SpiritualFervor",
    "stillsuit_manufacturer": "ImperiumArchetypes.Immortality.StillsuitManufacturer",
    "throne_room_politics": "ImperiumArchetypes.Immortality.ThroneRoomPolitics",
    "tleilaxu_master": "ImperiumArchetypes.Immortality.TleilaxuMaster",
    "tleilaxu_surgeon": "ImperiumArchetypes.Immortality.TleilaxuSurgeon",
    # Immortality Tleilaxu cards (instance ids ``tleilaxu:<id>:<n>``): the 18
    # deck cards, the fixed Reclaimed Forces slot and the promo Piter.
    "beguiling_pheromones": "TleilaxuArchetypes.Immortality.BeguilingPheromones",
    "chairdog": "TleilaxuArchetypes.Immortality.Chairdog",
    "contaminator": "TleilaxuArchetypes.Immortality.Contaminator",
    "corrino_genes": "TleilaxuArchetypes.Immortality.CorrinoGenes",
    "face_dancer": "TleilaxuArchetypes.Immortality.FaceDancer",
    "face_dancer_initiate": "TleilaxuArchetypes.Immortality.FaceDancerInitiate",
    "from_the_tanks": "TleilaxuArchetypes.Immortality.FromtheTanks",
    "ghola": "TleilaxuArchetypes.Immortality.Ghola",
    "guild_impersonator": "TleilaxuArchetypes.Immortality.GuildImpersonator",
    "industrial_espionage": "TleilaxuArchetypes.Immortality.IndustrialEspionage",
    "scientific_breakthrough": "TleilaxuArchetypes.Immortality.ScientificBreakthrough",
    "slig_farmer": "TleilaxuArchetypes.Immortality.SligFarmer",
    "stitched_horror": "TleilaxuArchetypes.Immortality.StitchedHorror",
    "subject_x_137": "TleilaxuArchetypes.Immortality.SubjectX137",
    "tleilaxu_infiltrator": "TleilaxuArchetypes.Immortality.TleilaxuInfiltrator",
    "twisted_mentat": "TleilaxuArchetypes.Immortality.TwistedMentat",
    "unnatural_reflexes": "TleilaxuArchetypes.Immortality.UnnaturalReflexes",
    "usurp": "TleilaxuArchetypes.Immortality.Usurp",
    "reclaimed_forces": "TleilaxuArchetypes.Immortality.ReclaimedForces",
    "piter_genius_advisor": "TleilaxuArchetypes.Promo.PiterGeniusAdvisor",
    # Epic Game Mode starter (the app's ``Decks.EpicStarterDeck``).
    "control_the_spice": "ImperiumArchetypes.RiseOfIx.ControltheSpice",
    # Bloodlines (app-style, bloodlines-cards.md §3): the 25 retail cards, the
    # CHOAM-only and Tech-only cards, and the promo Ruthless Leadership.
    "ruthless_leadership": "ImperiumArchetypes.AppStyle.RuthlessLeadership",
    "arrakis_observer": "ImperiumArchetypes.AppStyle.ArrakisObserver",
    "bombast": "ImperiumArchetypes.AppStyle.Bombast",
    "choam_demands": "ImperiumArchetypes.AppStyle.CHOAMDemands",
    "command_center": "ImperiumArchetypes.AppStyle.CommandCenter",
    "corrupt_bureaucrat": "ImperiumArchetypes.AppStyle.CorruptBureaucrat",
    "delivery_logistics": "ImperiumArchetypes.AppStyle.DeliveryLogistics",
    "disruption_tactics": "ImperiumArchetypes.AppStyle.DisruptionTactics",
    "eliminate_allies": "ImperiumArchetypes.AppStyle.EliminateAllies",
    "elite_forces": "ImperiumArchetypes.AppStyle.EliteForces",
    "engineered_miracle": "ImperiumArchetypes.AppStyle.EngineeredMiracle",
    "fremen_war_name": "ImperiumArchetypes.AppStyle.FremenWarName",
    "holy_war": "ImperiumArchetypes.AppStyle.HolyWar",
    "i_believe": "ImperiumArchetypes.AppStyle.IBelieve",
    "imperial_throneship": "ImperiumArchetypes.AppStyle.ImperialThroneship",
    "intelligence_training": "ImperiumArchetypes.AppStyle.IntelligenceTraining",
    "ixian_ambassador": "ImperiumArchetypes.AppStyle.IxianAmbassador",
    "litany_against_fear": "ImperiumArchetypes.AppStyle.LitanyAgainstFear",
    "mercantile_affairs": "ImperiumArchetypes.AppStyle.MercantileAffairs",
    "pointing_the_way": "ImperiumArchetypes.AppStyle.PointingtheWay",
    "possible_futures": "ImperiumArchetypes.AppStyle.PossibleFutures",
    "quash_rebellion": "ImperiumArchetypes.AppStyle.QuashRebellion",
    "sandwalk": "ImperiumArchetypes.AppStyle.Sandwalk",
    "sardaukar_standard": "ImperiumArchetypes.AppStyle.SardaukarStandard",
    "shrouded_counsel": "ImperiumArchetypes.AppStyle.ShroudedCounsel",
    "southern_faith": "ImperiumArchetypes.AppStyle.SouthernFaith",
    "urgent_shigawire": "ImperiumArchetypes.AppStyle.UrgentShigawire",
}
# intrigue card_id -> app archetype short name.
INTRIGUE_ARCHETYPES: dict[str, str] = {
    "backed_by_choam": "IntrigueArchetypes.Uprising.BackedbyCHOAM",
    "buy_access": "IntrigueArchetypes.Uprising.BuyAccess",
    "call_to_arms": "IntrigueArchetypes.Uprising.CalltoArms",
    "change_allegiances": "IntrigueArchetypes.Uprising.ChangeAllegiances",
    "choam_profits": "IntrigueArchetypes.Uprising.CHOAMProfits",
    "contingency_plan": "IntrigueArchetypes.Uprising.ContingencyPlan",
    "councilor_s_ambition": "IntrigueArchetypes.Uprising.CouncilorsAmbition",
    "crysknife": "IntrigueArchetypes.Uprising.CrysknifeIntrigue",
    "cunning": "IntrigueArchetypes.Uprising.Cunning",
    "depart_for_arrakis": "IntrigueArchetypes.Uprising.DepartforArrakis",
    "desert_mouse": "IntrigueArchetypes.Uprising.DesertMouse",
    "detonation": "IntrigueArchetypes.Uprising.Detonation",
    "devour": "IntrigueArchetypes.Uprising.Devour",
    "distraction": "IntrigueArchetypes.Uprising.Distraction",
    "find_weakness": "IntrigueArchetypes.Uprising.FindWeakness",
    "go_to_ground": "IntrigueArchetypes.Uprising.GotoGround",
    "imperium_politics": "IntrigueArchetypes.Uprising.ImperiumPolitics",
    "impress": "IntrigueArchetypes.Uprising.Impress",
    "inspire_awe": "IntrigueArchetypes.Uprising.InspireAwe",
    "intelligence_report": "IntrigueArchetypes.Uprising.IntelligenceReport",
    "leverage": "IntrigueArchetypes.Uprising.Leverage",
    "manipulate": "IntrigueArchetypes.Uprising.ManipulateIntrigue",
    "market_opportunity": "IntrigueArchetypes.Uprising.MarketOpportunity",
    "mercenaries": "IntrigueArchetypes.Uprising.Mercenaries",
    "opportunism": "IntrigueArchetypes.Uprising.Opportunism",
    "ornithopter": "IntrigueArchetypes.Uprising.Ornithopter",
    "questionable_methods": "IntrigueArchetypes.Uprising.QuestionableMethods",
    "reach_agreement": "IntrigueArchetypes.Uprising.ReachAgreement",
    "secure_spice_trade": "IntrigueArchetypes.Uprising.SecureSpiceTrade",
    "shaddam_s_favor": "IntrigueArchetypes.Uprising.ShaddamsFavor",
    "shadow_alliance": "IntrigueArchetypes.Uprising.ShadowAlliance",
    "sietch_ritual": "IntrigueArchetypes.Uprising.SietchRitual",
    "special_mission": "IntrigueArchetypes.Uprising.SpecialMission",
    "spice_is_power": "IntrigueArchetypes.Uprising.SpiceIsPower",
    "spring_the_trap": "IntrigueArchetypes.Uprising.SpringtheTrap",
    "strategic_stockpiling": "IntrigueArchetypes.Uprising.StrategicStockpiling",
    "tactical_option": "IntrigueArchetypes.Uprising.TacticalOption",
    "unexpected_allies": "IntrigueArchetypes.Uprising.UnexpectedAllies",
    "weirding_combat": "IntrigueArchetypes.Uprising.WeirdingCombat",
    # Immortality (``intrigue_cards_for_choam(..., immortality=True)``).
    "breakthrough": "IntrigueArchetypes.Immortality.Breakthrough",
    "counterattack": "IntrigueArchetypes.Immortality.Counterattack",
    "disguised_bureaucrat": "IntrigueArchetypes.Immortality.DisguisedBureaucrat",
    "economic_positioning": "IntrigueArchetypes.Immortality.EconomicPositioning",
    "gruesome_sacrifice": "IntrigueArchetypes.Immortality.GruesomeSacrifice",
    "harvest_cells": "IntrigueArchetypes.Immortality.HarvestCells",
    "illicit_dealings": "IntrigueArchetypes.Immortality.IllicitDealings",
    "shadowy_bargain": "IntrigueArchetypes.Immortality.ShadowyBargain",
    "study_melange": "IntrigueArchetypes.Immortality.StudyMelange",
    "tleilaxu_puppet": "IntrigueArchetypes.Immortality.TleilaxuPuppet",
    "vicious_talents": "IntrigueArchetypes.Immortality.ViciousTalents",
    # Bloodlines (app-style, bloodlines-cards.md §4), CHOAM-only and
    # Tech-only cards included.
    "adaptive_tactics": "IntrigueArchetypes.AppStyle.AdaptiveTactics",
    "battlefield_research": "IntrigueArchetypes.AppStyle.BattlefieldResearch",
    "coercive_negotiation": "IntrigueArchetypes.AppStyle.CoerciveNegotiation",
    "desert_support": "IntrigueArchetypes.AppStyle.DesertSupport",
    "emperor_s_invitation": "IntrigueArchetypes.AppStyle.EmperorsInvitation",
    "false_orders": "IntrigueArchetypes.AppStyle.FalseOrders",
    "grasp_arrakis": "IntrigueArchetypes.AppStyle.GraspArrakis",
    "honor_guard": "IntrigueArchetypes.AppStyle.HonorGuard",
    "insider_information": "IntrigueArchetypes.AppStyle.InsiderInformation",
    "rapid_engineering": "IntrigueArchetypes.AppStyle.RapidEngineering",
    "return_the_favor": "IntrigueArchetypes.AppStyle.ReturntheFavor",
    "ripples_in_the_sand": "IntrigueArchetypes.AppStyle.RipplesintheSand",
    "sacred_pools": "IntrigueArchetypes.AppStyle.SacredPools",
    "seize_production": "IntrigueArchetypes.AppStyle.SeizeProduction",
    "sleeper_unit": "IntrigueArchetypes.AppStyle.SleeperUnit",
    "tenuous_bond": "IntrigueArchetypes.AppStyle.TenuousBond",
    "the_strong_survive": "IntrigueArchetypes.AppStyle.TheStrongSurvive",
    "withdrawal_agreement": "IntrigueArchetypes.AppStyle.WithdrawalAgreement",
    # Piter De Vries' Twisted Intrigue (bloodlines-cards.md §5): ordinary
    # Intrigue cards once held (instance ids ``intrigue:twisted_<id>:0``).
    "twisted_ambitious": "IntrigueArchetypes.AppStyle.TwistedAmbitious",
    "twisted_calculating": "IntrigueArchetypes.AppStyle.TwistedCalculating",
    "twisted_controlled": "IntrigueArchetypes.AppStyle.TwistedControlled",
    "twisted_devious": "IntrigueArchetypes.AppStyle.TwistedDevious",
    "twisted_discerning": "IntrigueArchetypes.AppStyle.TwistedDiscerning",
    "twisted_insidious": "IntrigueArchetypes.AppStyle.TwistedInsidious",
    "twisted_resourceful": "IntrigueArchetypes.AppStyle.TwistedResourceful",
    "twisted_sadistic": "IntrigueArchetypes.AppStyle.TwistedSadistic",
    "twisted_shrewd": "IntrigueArchetypes.AppStyle.TwistedShrewd",
    "twisted_sinister": "IntrigueArchetypes.AppStyle.TwistedSinister",
    "twisted_unnatural": "IntrigueArchetypes.AppStyle.TwistedUnnatural",
    "twisted_withdrawn": "IntrigueArchetypes.AppStyle.TwistedWithdrawn",
}
# Navigation card_id -> archetype (Steersman Y'rkoon's ten cards; not Intrigue
# cards, bloodlines-systems.md §5; instance ids ``intrigue:navigation_card_<n>:0``).
NAVIGATION_ARCHETYPES: dict[str, str] = {
    f"navigation_card_{n}": f"NavigationArchetypes.AppStyle.NavigationCard{n}"
    for n in range(1, 11)
}
# space_id -> (archetype without CHOAM, archetype with CHOAM).
SPACE_ARCHETYPES: dict[str, tuple[str, str]] = {
    "dutiful_service": (
        "SpaceArchetypes.Uprising.DutifulServiceUP",
        "SpaceArchetypes.Uprising.DutifulServiceCHOAM",
    ),
    "sardaukar": _both("SpaceArchetypes.Uprising.Sardaukar"),
    "deliver_supplies": _both("SpaceArchetypes.Uprising.DeliverSupplies"),
    "heighliner": _both("SpaceArchetypes.Uprising.HeighlinerUP"),
    "espionage": _both("SpaceArchetypes.Uprising.Espionage"),
    "secrets": _both("SpaceArchetypes.BaseSet.Secrets"),
    "desert_tactics": _both("SpaceArchetypes.Uprising.DesertTactics"),
    "fremkit": _both("SpaceArchetypes.Uprising.Fremkit"),
    "assembly_hall": _both("SpaceArchetypes.Uprising.AssemblyHall"),
    "gather_support": _both("SpaceArchetypes.Uprising.GatherSupport"),
    "high_council": _both("SpaceArchetypes.Uprising.HighCouncilUP"),
    "imperial_privilege": _both("SpaceArchetypes.Uprising.ImperialPrivilege"),
    "swordmaster": _both("SpaceArchetypes.Uprising.SwordmasterUP"),
    "arrakeen": _both("SpaceArchetypes.BaseSet.Arrakeen"),
    "research_station": _both("SpaceArchetypes.Uprising.ResearchStationUP"),
    "sietch_tabr": _both("SpaceArchetypes.Uprising.SietchTabrUP"),
    "spice_refinery": _both("SpaceArchetypes.Uprising.SpiceRefinery"),
    "accept_contract": (
        "SpaceArchetypes.Uprising.AcceptContractUP",
        "SpaceArchetypes.Uprising.AcceptContractCHOAM",
    ),
    "deep_desert": _both("SpaceArchetypes.Uprising.DeepDesert"),
    "hagga_basin": _both("SpaceArchetypes.Uprising.HaggaBasinUP"),
    "imperial_basin": _both("SpaceArchetypes.BaseSet.ImperialBasin"),
    "shipping": _both("SpaceArchetypes.Uprising.Shipping"),
}
# space_id -> the archetype that replaces it when Immortality is on (spec
# immortality.md §1.1: ``ResearchStationUP`` has ``RemovedFromSetList =
# [Immortality]``).
IMMORTALITY_SPACE_ARCHETYPES: dict[str, str] = {
    "research_station": "SpaceArchetypes.Immortality.ResearchStationImmortality",
}
# Bloodlines spaces with no app archetype (bloodlines-systems.md §6). Kept out
# of ``SPACE_ARCHETYPES``: Tuek's Sietch is on the board only while Esmar Tuek
# plays (``BoardSpace.required_leader_id``), and the profile reads
# ``SPACE_ARCHETYPES`` as every space of every game.
BLOODLINES_SPACE_ARCHETYPES: dict[str, str] = {
    "tuek_sietch": "SpaceArchetypes.AppStyle.TueksSietch",
}
#: Where a Bloodlines space goes in the app's space order: after every app
#: space. ``BeginSetup`` appends each further enabled set's spaces after the
#: board set's (``windows/turn.board_space_order``), and a synthetic archetype
#: comes after every app type (spec silent on the order; app-style choice).
BLOODLINES_SPACE_ORDER: tuple[str, ...] = ("tuek_sietch",)


def board_space_ids(board: Board) -> tuple[str, ...]:
    """Every board space of this game, in catalog order (``BoardSpaces``).

    The app's spaces, then Tuek's Sietch when Esmar Tuek is in the game
    (``Board.tueks_sietch``, plan §11.8).
    """

    if board.tueks_sietch:
        return (*SPACE_ARCHETYPES, *BLOODLINES_SPACE_ORDER)
    return tuple(SPACE_ARCHETYPES)


def is_board_space(space_id: str) -> bool:
    """Whether ``space_id`` names a board space of any game (app or Bloodlines)."""

    return space_id in SPACE_ARCHETYPES or space_id in BLOODLINES_SPACE_ARCHETYPES


# -- board overlays (see the module docstring) ------------------------------------

_AS_BLOODLINES = "worm.canis.abilities.AppStyle.Bloodlines."
_AS_SCOUTS = "worm.canis.abilities.AppStyle.Scouts."
#: bloodlines-systems.md §6: the six spaces a Sardaukar Commander is set on
#: (``content/bloodlines/sardaukar.py`` ``COMMANDER_SETUP_SPACE_IDS``).
COMMANDER_SPACES: tuple[str, ...] = (
    "sardaukar",
    "dutiful_service",
    "deliver_supplies",
    "high_council",
    "gather_support",
    "assembly_hall",
)
ACQUIRE_COMMANDER_ABILITY: Final = _AS_BLOODLINES + "AcquireCommanderAbility"
#: bloodlines-systems.md §6: the Ixian Embassy's Acquire Tech on a Landsraad
#: visit (the five Landsraad-icon spaces).
TECH_SPACES: tuple[str, ...] = (
    "high_council",
    "imperial_privilege",
    "swordmaster",
    "assembly_hall",
    "gather_support",
)
ACQUIRE_TECH_ABILITY: Final = (
    "worm.canis.abilities.ActivatedAbilities.RiseOfIx.AcquireTechAbility"
)
#: scouts.md §4.1, §4.5, §4.2.
MISSION_PIECES_ABILITY: Final = _AS_SCOUTS + "MissionPiecesSpaceAbility"
SUBCOMMITTEE_OFFER_ABILITY: Final = _AS_SCOUTS + "SubcommitteeOfferAbility"
SUBCOMMITTEE_SPACES: tuple[str, ...] = ("high_council",)
HAGGA_BASIN_DEFERRED: Final = (
    "worm.canis.abilities.SpaceAbilities.Uprising.HaggaBasinUprisingDeferredAbility"
)
DESERT_RIDING_ABILITY: Final = _AS_SCOUTS + "DesertRidingAbility"
#: scouts.md §4.7 (Eyes on Arrakis): the Faction spaces that are not Combat
#: spaces (``rules/scouts_modifiers.py`` ``space_is_combat``).
EYES_ON_ARRAKIS_SPACES: tuple[str, ...] = (
    "dutiful_service",
    "sardaukar",
    "deliver_supplies",
    "espionage",
    "secrets",
)
DEPLOY_UNITS_ABILITY: Final = (
    "worm.canis.abilities.ActivatedAbilities.DeployUnitsAbility"
)
# conflict card_id -> (archetype without CHOAM, archetype with CHOAM).
CONFLICT_ARCHETYPES: dict[str, tuple[str, str]] = {
    "skirmish_crysknife": _both("ConflictArchetypes.Uprising.SkirmishH"),
    "skirmish_ornithopter": _both("ConflictArchetypes.Uprising.SkirmishG"),
    "skirmish_desert_mouse": _both("ConflictArchetypes.Uprising.SkirmishI"),
    "choam_security": (
        "ConflictArchetypes.Uprising.CHOAMSecurityUP",
        "ConflictArchetypes.Uprising.CHOAMSecurityCHOAM",
    ),
    "spice_freighters": _both("ConflictArchetypes.Uprising.SpiceFreightersUP"),
    "siege_of_arrakeen": _both("ConflictArchetypes.Uprising.SiegeofArrakeenUP"),
    "seize_spice_refinery": _both("ConflictArchetypes.Uprising.SeizeSpiceRefineryUP"),
    "test_of_loyalty": _both("ConflictArchetypes.Uprising.TestofLoyaltyUP"),
    "shadow_contest": _both("ConflictArchetypes.Uprising.ShadowContestUP"),
    "secure_imperial_basin": _both("ConflictArchetypes.Uprising.SecureImperialBasinUP"),
    "protect_the_sietches": _both("ConflictArchetypes.Uprising.ProtecttheSietchesUP"),
    "trade_dispute": (
        "ConflictArchetypes.Uprising.TradeDisputeUP",
        "ConflictArchetypes.Uprising.TradeDisputeCHOAM",
    ),
    "propaganda": _both("ConflictArchetypes.Uprising.PropagandaUP"),
    "battle_for_imperial_basin": _both(
        "ConflictArchetypes.Uprising.BattleforImperialBasinUP"
    ),
    "battle_for_arrakeen": _both("ConflictArchetypes.Uprising.BattleforArrakeenUP"),
    "battle_for_spice_refinery": _both(
        "ConflictArchetypes.Uprising.BattleforSpiceRefineryUP"
    ),
    # Epic Game Mode's Conflict III (the app's Rise of Ix card).
    "economic_supremacy": _both("ConflictArchetypes.RiseOfIx.EconomicSupremacy"),
    # Bloodlines' Conflict I and II (app-style, bloodlines-cards.md §6).
    "skirmish_wild": _both("ConflictArchetypes.AppStyle.SkirmishWild"),
    "storms_in_the_south": _both("ConflictArchetypes.AppStyle.StormsintheSouth"),
}
# contract card_id -> app archetype short name.
CONTRACT_ARCHETYPES: dict[str, str] = {
    "acquire": "ContractArchetypes.Uprising.ContractBase_20",
    "arrakeen_i": "ContractArchetypes.Uprising.ContractBase_5",
    "arrakeen_ii": "ContractArchetypes.Uprising.ContractBase_4",
    "deliver_supplies": "ContractArchetypes.Uprising.ContractBase_14",
    "espionage_i": "ContractArchetypes.Uprising.ContractBase_17",
    "espionage_i_copy_2": "ContractArchetypes.Uprising.ContractBase_17",
    "harvest_3": "ContractArchetypes.Uprising.ContractBase_1",
    "harvest_3_copy_2": "ContractArchetypes.Uprising.ContractBase_1",
    "harvest_4": "ContractArchetypes.Uprising.ContractBase_3",
    "spice_refinery_i": "ContractArchetypes.Uprising.ContractBase_6",
    "heighliner_i": "ContractArchetypes.Uprising.ContractBase_16",
    "heighliner_ii": "ContractArchetypes.Uprising.ContractBase_15",
    "spice_refinery_ii": "ContractArchetypes.Uprising.ContractBase_7",
    "high_council_i": "ContractArchetypes.Uprising.ContractBase_10",
    "high_council_ii": "ContractArchetypes.Uprising.ContractBase_11",
    "immediate": "ContractArchetypes.Uprising.ContractBase_19",
    "research_station_i": "ContractArchetypes.Uprising.ContractBase_9",
    "research_station_ii": "ContractArchetypes.Uprising.ContractBase_8",
    "sardaukar_i": "ContractArchetypes.Uprising.ContractBase_12",
    "sardaukar_ii": "ContractArchetypes.Uprising.ContractBase_13",
    # Bloodlines' eight tokens (app-style, bloodlines-cards.md §7).
    "bloodlines_deliver_supplies": (
        "ContractArchetypes.AppStyle.BloodlinesDeliverSupplies"
    ),
    "bloodlines_earn_any_alliance": (
        "ContractArchetypes.AppStyle.BloodlinesEarnAnyAlliance"
    ),
    "bloodlines_harvest_3": "ContractArchetypes.AppStyle.BloodlinesHarvest3",
    "bloodlines_harvest_4": "ContractArchetypes.AppStyle.BloodlinesHarvest4",
    "bloodlines_high_council": "ContractArchetypes.AppStyle.BloodlinesHighCouncil",
    "bloodlines_immediate": "ContractArchetypes.AppStyle.BloodlinesImmediate",
    "bloodlines_secrets": "ContractArchetypes.AppStyle.BloodlinesSecrets",
    "bloodlines_spice_refinery": "ContractArchetypes.AppStyle.BloodlinesSpiceRefinery",
}
# leader_id -> app archetype short name (incl. Lady Jessica's flipped face).
LEADER_ARCHETYPES: dict[str, str] = {
    "feyd_rautha_harkonnen": "LeaderArchetypes.Uprising.FeydRauthaHarkonnen",
    "gurney_halleck": "LeaderArchetypes.Uprising.GurneyHalleckLeader",
    "lady_amber_metulli": "LeaderArchetypes.Uprising.LadyAmberMetulli",
    "lady_jessica": "LeaderArchetypes.Uprising.LadyJessicaLeader",
    "lady_margot_fenring": "LeaderArchetypes.Uprising.LadyMargotFenring",
    "muad_dib": "LeaderArchetypes.Uprising.MuadDib",
    "princess_irulan": "LeaderArchetypes.Uprising.PrincessIrulan",
    "staban_tuek": "LeaderArchetypes.Uprising.StabanTuek",
    "shaddam_corrino_iv": "LeaderArchetypes.Uprising.ShaddamCorrinoIV",
    # Lady Jessica's flipped face (``PublicPlayerView.leader_face_id``).
    "reverend_mother_jessica": "LeaderArchetypes.Uprising.ReverendMotherJessica",
    # Bloodlines leaders (app-style, bloodlines-systems.md §4; none has a
    # second face).
    "chani": "LeaderArchetypes.AppStyle.ChaniLeader",
    "count_hasimir_fenring": "LeaderArchetypes.AppStyle.CountHasimirFenring",
    "duncan_idaho": "LeaderArchetypes.AppStyle.DuncanIdahoLeader",
    "esmar_tuek": "LeaderArchetypes.AppStyle.EsmarTuekLeader",
    "gaius_helen_mohiam": "LeaderArchetypes.AppStyle.GaiusHelenMohiam",
    "piter_de_vries": "LeaderArchetypes.AppStyle.PiterDeVriesLeader",
    "steersman_y_rkoon": "LeaderArchetypes.AppStyle.SteersmanYrkoonLeader",
    "liet_kynes": "LeaderArchetypes.AppStyle.LietKynesLeader",
    "kota_odax_of_ix": "LeaderArchetypes.AppStyle.KotaOdaxOfIx",
}
# tech_id -> Tech tile archetype (app-style, bloodlines-systems.md §3.2).
TECH_ARCHETYPES: dict[str, str] = {
    "advanced_data_analysis": "TechTileArchetypes.AppStyle.AdvancedDataAnalysis",
    "choam_transports": "TechTileArchetypes.AppStyle.CHOAMTransports",
    "delivery_bay": "TechTileArchetypes.AppStyle.DeliveryBay",
    "forbidden_weapons": "TechTileArchetypes.AppStyle.ForbiddenWeapons",
    "gene_locked_vault": "TechTileArchetypes.AppStyle.GeneLockedVault",
    "glowglobes": "TechTileArchetypes.AppStyle.Glowglobes",
    "navigation_chamber": "TechTileArchetypes.AppStyle.NavigationChamber",
    "ornithopter_fleet": "TechTileArchetypes.AppStyle.OrnithopterFleet",
    "panopticon": "TechTileArchetypes.AppStyle.Panopticon",
    "planetary_array": "TechTileArchetypes.AppStyle.PlanetaryArray",
    "plasteel_blades": "TechTileArchetypes.AppStyle.PlasteelBlades",
    "rapid_dropships": "TechTileArchetypes.AppStyle.RapidDropships",
    "sardaukar_high_command": "TechTileArchetypes.AppStyle.SardaukarHighCommand",
    "self_destroying_messages": "TechTileArchetypes.AppStyle.SelfDestroyingMessages",
    "servo_receivers": "TechTileArchetypes.AppStyle.ServoReceivers",
    "spy_drones": "TechTileArchetypes.AppStyle.SpyDrones",
    "suspensor_suits": "TechTileArchetypes.AppStyle.SuspensorSuits",
    "training_depot": "TechTileArchetypes.AppStyle.TrainingDepot",
}
# The Sardaukar Commander and skill_id -> Skill archetype (app-style,
# bloodlines-systems.md §2.1).
COMMANDER_ARCHETYPE: Final = "CommanderArchetypes.AppStyle.SardaukarCommander"
SKILL_ARCHETYPES: dict[str, str] = {
    "canny": "SkillArchetypes.AppStyle.Canny",
    "charismatic": "SkillArchetypes.AppStyle.Charismatic",
    "desperate": "SkillArchetypes.AppStyle.Desperate",
    "driven": "SkillArchetypes.AppStyle.Driven",
    "fierce": "SkillArchetypes.AppStyle.Fierce",
    "hardy": "SkillArchetypes.AppStyle.Hardy",
    "loyal": "SkillArchetypes.AppStyle.Loyal",
}
# "<Scouts item id>:<line index>" -> line archetype (app-style, scouts.md §2.2,
# §5): the generated table. Line index = our option index (the event's
# options, then its secret choices; a sealed auction's place - 1; a mission's
# join line).
SCOUTS_LINE_ARCHETYPES: Final = SCOUTS_LINES
# post_id -> the app's observation post index (1-13).
POST_INDEX: dict[str, int] = {
    "emperor-sardaukar-dutiful-service": 1,
    "spacing-guild-heighliner-deliver-supplies": 2,
    "bene-gesserit-espionage-secrets": 3,
    "fremen-desert-tactics-fremkit": 4,
    "landsraad-high-council-imperial-privilege-swordmaster": 5,
    "landsraad-assembly-hall-gather-support": 6,
    "choam-shipping-accept-contract": 7,
    "arrakis-research-station-sietch-tabr": 8,
    "arrakis-research-station-spice-refinery": 9,
    "arrakis-spice-refinery-arrakeen": 10,
    "arrakis-deep-desert": 11,
    "arrakis-hagga-basin": 12,
    "arrakis-imperial-basin": 13,
}
# our faction id -> the app's Factions enum name.
FACTION_NAMES: dict[str, str] = {
    "emperor": "Emperor",
    "spacing_guild": "SpacingGuild",
    "bene_gesserit": "BeneGesserit",
    "fremen": "Fremen",
}


def archetype(short: str) -> Archetype:
    """The archetype of a short name: the app's, else the app-style one."""

    found = ARCHETYPES.get(short)
    return SYNTHETIC[short] if found is None else found


_archetype = archetype


def card_entity(instance_id: str, owner: int | None = None) -> Entity:
    """A personal card (starter, reserve or Imperium) by instance id."""

    return Entity(
        Kind.CARD, instance_id, _archetype(CARD_ARCHETYPES[card_id(instance_id)]), owner
    )


def intrigue_entity(instance_id: str, owner: int | None = None) -> Entity:
    """An Intrigue card by instance id."""

    return Entity(
        Kind.INTRIGUE,
        instance_id,
        _archetype(INTRIGUE_ARCHETYPES[card_id(instance_id)]),
        owner,
    )


def contract_entity(instance_id: str, owner: int | None = None) -> Entity:
    """A CHOAM contract by instance id (``contract:<id>``)."""

    return Entity(
        Kind.CONTRACT,
        instance_id,
        _archetype(CONTRACT_ARCHETYPES[card_id(instance_id)]),
        owner,
    )


def space_archetype(space_id: str, board: Board) -> str:
    """The app archetype short name of a board space in this game."""

    if board.immortality and space_id in IMMORTALITY_SPACE_ARCHETYPES:
        return IMMORTALITY_SPACE_ARCHETYPES[space_id]
    if space_id in BLOODLINES_SPACE_ARCHETYPES:
        return BLOODLINES_SPACE_ARCHETYPES[space_id]
    without, with_choam = SPACE_ARCHETYPES[space_id]
    return with_choam if board.choam else without


def _space_overlay(space_id: str, board: Board) -> tuple[tuple[str, ...], bool]:
    """The ability ids a board option adds to a space, and whether it makes
    the space a Combat space (see the module docstring)."""

    added: list[str] = []
    if board.bloodlines and space_id in COMMANDER_SPACES:
        added.append(ACQUIRE_COMMANDER_ABILITY)
    if board.tech_module and space_id in TECH_SPACES:
        added.append(ACQUIRE_TECH_ABILITY)
    if board.scouts:
        if space_id in SUBCOMMITTEE_SPACES:
            added.append(SUBCOMMITTEE_OFFER_ABILITY)
        added.append(MISSION_PIECES_ABILITY)
    combat = board.faction_spaces_combat and space_id in EYES_ON_ARRAKIS_SPACES
    if combat:
        added.append(DEPLOY_UNITS_ABILITY)
    return tuple(added), combat


@cache
def _space_archetype(space_id: str, board: Board) -> Archetype:
    """The space's archetype with this game's overlays (the app's own object
    when no option changes it)."""

    base = _archetype(space_archetype(space_id, board))
    added, combat = _space_overlay(space_id, board)
    ids = base.attributes.get("WormAbilityIDs", ())
    assert isinstance(ids, tuple)
    swap = board.scouts and HAGGA_BASIN_DEFERRED in ids
    if not (added or combat or swap):
        return base
    if swap:
        ids = tuple(
            DESERT_RIDING_ABILITY if i == HAGGA_BASIN_DEFERRED else i for i in ids
        )
    attributes = dict(base.attributes)
    attributes["WormAbilityIDs"] = (*ids, *added)
    if combat:
        attributes["CombatSpace"] = True
    return Archetype(
        short=base.short,
        kind=base.kind,
        title=base.title,
        in_uprising=base.in_uprising,
        in_uprising_choam=base.in_uprising_choam,
        attributes=MappingProxyType(attributes),
    )


def space_entity(space_id: str, board: Board) -> Entity:
    """A board space (with the board overlays of this game's options)."""

    return Entity(Kind.SPACE, space_id, _space_archetype(space_id, board))


def conflict_entity(conflict_id: str, choam: bool) -> Entity:
    """A Conflict card."""

    without, with_choam = CONFLICT_ARCHETYPES[conflict_id]
    return Entity(
        Kind.CONFLICT, conflict_id, _archetype(with_choam if choam else without)
    )


def conflict_reward_entities(conflict_id: str, choam: bool) -> tuple[Entity, ...]:
    """The 1st/2nd/3rd reward archetypes of a Conflict card, in place order.

    Read from the card archetype's ``ConflictRewardArchetypes``.
    """

    card = conflict_entity(conflict_id, choam)
    return tuple(
        Entity(Kind.CONFLICT, conflict_id, _archetype(short))
        for short in card.list_attr("ConflictRewardArchetypes")
    )


def leader_entity(leader_id: str, face_id: str | None = None) -> Entity:
    """A leader (the flipped face when ``face_id`` names one)."""

    key = face_id if face_id and face_id in LEADER_ARCHETYPES else leader_id
    return Entity(Kind.LEADER, leader_id, _archetype(LEADER_ARCHETYPES[key]))


def post_entity(post_id: str, owner: int | None = None) -> Entity:
    """An observation post (the app's ``WormObservationPost``)."""

    return Entity(Kind.POST, post_id, None, owner)


def spy_entity(post_id: str, owner: int) -> Entity:
    """A spy standing on ``post_id``."""

    return Entity(Kind.SPY, post_id, None, owner)


def agent_entity(space_id: str, owner: int) -> Entity:
    """An agent standing on ``space_id``."""

    return Entity(Kind.AGENT, space_id, None, owner)


def track_entity(faction: str) -> Entity:
    """A faction influence track (our faction id)."""

    return Entity(Kind.TRACK, faction, None)


# -- app-style entities (docs/app-ai-plan.md §11.3) --------------------------------


def tech_entity(tech_id: str, owner: int | None = None) -> Entity:
    """A Bloodlines Tech tile by our ``tech_id`` (``Kind.TECH``; the same
    entity ``profile.tech.tech_tile_entity`` builds from the archetype)."""

    return Entity(Kind.TECH, tech_id, _archetype(TECH_ARCHETYPES[tech_id]), owner)


def commander_entity(
    ref: str = "sardaukar_commander", owner: int | None = None
) -> Entity:
    """A Sardaukar Commander. Commanders have no id in our engine; ``ref``
    names where it stands (a space id, ``"bank"``) when that matters."""

    return Entity(Kind.COMMANDER, ref, _archetype(COMMANDER_ARCHETYPE), owner)


def skill_id_of(skill: str) -> str:
    """The skill id of a Skill tile instance id (``skill:<id>:<copy>``) or of
    a bare skill id."""

    return skill.split(":")[1] if skill.startswith("skill:") else skill


def skill_entity(skill: str, owner: int | None = None) -> Entity:
    """A Skill tile, by skill id or tile instance id (the ``ref``)."""

    return Entity(
        Kind.SKILL, skill, _archetype(SKILL_ARCHETYPES[skill_id_of(skill)]), owner
    )


def navigation_entity(instance_id: str, owner: int | None = None) -> Entity:
    """One of Steersman Y'rkoon's Navigation cards (instance id
    ``intrigue:navigation_card_<n>:0``, or the bare card id)."""

    return Entity(
        Kind.NAVIGATION,
        instance_id,
        _archetype(NAVIGATION_ARCHETYPES[card_id(instance_id)]),
        owner,
    )


def scouts_line_entity(item_id: str, line: int, owner: int | None = None) -> Entity:
    """One Arrakeen Scouts cost -> reward line (``ref = "<item id>:<line>"``)."""

    ref = f"{item_id}:{line}"
    return Entity(Kind.SCOUTS, ref, _archetype(SCOUTS_LINE_ARCHETYPES[ref]), owner)
