"""Dune: Imperium - Immortality content definitions (``immortality`` option)."""

from dune_imperium.content.immortality.board import (
    FIRST_GENETIC_MARKER_COLUMN,
    RESEARCH_LAST_COLUMN,
    RESEARCH_SPACES,
    RESEARCH_SPACES_BY_ID,
    RESEARCH_START_ID,
    SECOND_GENETIC_MARKER_COLUMN,
    TLEILAXU_ROW_SIZE,
    TLEILAXU_SETUP_SPICE,
    TLEILAXU_SETUP_SPICE_SPACE,
    TLEILAXU_TRACK,
    TLEILAXU_TRACK_END,
    ResearchBonus,
    ResearchSpace,
    TleilaxuBonus,
    genetic_markers_reached,
    research_next_space_ids,
)
from dune_imperium.content.immortality.tleilaxu import (
    RECLAIMED_FORCES,
    TLEILAXU_CARDS,
    TLEILAXU_CARDS_BY_ID,
    TleilaxuCardEntry,
    tleilaxu_card_for_instance,
    tleilaxu_cards_for,
    tleilaxu_deck_instance_ids,
)

__all__ = [
    "FIRST_GENETIC_MARKER_COLUMN",
    "RECLAIMED_FORCES",
    "RESEARCH_LAST_COLUMN",
    "RESEARCH_SPACES",
    "RESEARCH_SPACES_BY_ID",
    "RESEARCH_START_ID",
    "SECOND_GENETIC_MARKER_COLUMN",
    "TLEILAXU_CARDS",
    "TLEILAXU_CARDS_BY_ID",
    "TLEILAXU_ROW_SIZE",
    "TLEILAXU_SETUP_SPICE",
    "TLEILAXU_SETUP_SPICE_SPACE",
    "TLEILAXU_TRACK",
    "TLEILAXU_TRACK_END",
    "ResearchBonus",
    "ResearchSpace",
    "TleilaxuBonus",
    "TleilaxuCardEntry",
    "genetic_markers_reached",
    "research_next_space_ids",
    "tleilaxu_card_for_instance",
    "tleilaxu_cards_for",
    "tleilaxu_deck_instance_ids",
]
