"""The app AI constant tables (``worm.canis.ai.AIConstantsRef`` and
its Medium/Easy subclasses), one field per getter in vtable order.

Generated by ``scripts/dwgr/app_ai_emit.py`` from app 4.1.2.1808
(build dad97e2021144d45b5b4f022e07bd3b3).
Do not edit by hand; re-run the extractor and the emitter instead.
Field names are the app's getter names without ``get_``.
"""

from dataclasses import dataclass
from types import MappingProxyType
from typing import Final


@dataclass(frozen=True, slots=True)
class AIConstants:
    """Every AI tuning constant of one difficulty table."""

    VictoryPointValueEarly: float
    VictoryPointValueMid: float
    VictoryPointValueLate: float
    PersuasionValueEarly: float
    PersuasionValueMid: float
    PersuasionValueLate: float
    StrengthValueEarly: float
    StrengthValueMid: float
    StrengthValueLate: float
    SolariValueEarly: float
    SolariValueMid: float
    SolariValueLate: float
    SolariMissingHighCouncilMod: float
    SolariMissingSwordmasterMod: float
    SpiceValueEarly: float
    SpiceValueMid: float
    SpiceValueLate: float
    BonusSpiceMod: float
    WaterValueEarly: float
    WaterValueMid: float
    WaterValueLate: float
    TroopValueEarly: float
    TroopValueMid: float
    TroopValueLate: float
    IntrigueValueEarly: float
    IntrigueValueMid: float
    IntrigueValueLate: float
    IntrigueStealBonus: float
    CardDrawValue: float
    TrashCardEarly: float
    TrashCardMid: float
    TrashCardLate: float
    DeployEarly: float
    DeployMid: float
    DeployLate: float
    SolariShortValue: float
    SpiceShortAmount: float
    TroopShortAmount: float
    WaterShortAmount: float
    AcquireNewIconsBonus: float
    ConsolidationValueMod: float
    SynergyModMaxValue: float
    SynergyTSMFCardValue: float
    SynergyTSMFHighPersuasionValue: float
    SynergyFremenWithBondInDeck: float
    SynergyBondWithFremenInDeck: float
    SynergyBeneGesseritWithBondInDeck: float
    SynergyWithFactionInDeck: float
    GainSwordmasterEarly: float
    GainSwordmasterMid: float
    GainSwordmasterLate: float
    GainHighCouncilEarly: float
    GainHighCouncilMid: float
    GainHighCouncilLate: float
    GainFoldspaceEarly: float
    GainFoldspaceMid: float
    GainFoldspaceLate: float
    GainMentatEarly: float
    GainMentatMid: float
    GainMentatLate: float
    SellMelangeLowSolariValueThreshold: float
    SellMelangeMidSolariValueThreshold: float
    SellMelangeHighSolariValueThreshold: float
    SellMelangeSpaceBonus: float
    ConspireSpaceBonus: float
    HeighlinerSpaceBonus: float
    HeighlinerSpaceLowSupplyPenalty: float
    HeighlinerSpaceEarlyInRoundPenalty: float
    ControlSolariEarly: float
    ControlSolariMid: float
    ControlSolariLate: float
    ControlSpiceEarly: float
    ControlSpiceMid: float
    ControlSpiceLate: float
    InfluenceValue: float
    GainInfluenceDefendAllianceMod: float
    GainInfluenceDefendAllianceThreatenedMod: float
    GainInfluenceVictoryPointMod: float
    GainInfluenceVictoryPointLateMod: float
    GainInfluenceAllianceMod: float
    GainInfluenceAllianceLateMod: float
    GainInfluenceThreatenedAllianceMod: float
    GainInfluenceStealAllianceMod: float
    GainInfluenceStealAllianceEndgameMod: float
    GainInfluenceThreatenAllianceMod: float
    GainInfluenceSecureAllianceMod: float
    GainInfluenceAllianceImpossibleMod: float
    GainInfluenceAllianceUnlikelyMod: float
    GainInfluenceCardAllianceBonusMod: float
    LoseInfluenceForfeitAllianceMod: float
    LoseInfluenceForfeitAllianceCushionMod: float
    LoseInfluenceForfeitVictoryPoint: float
    LoseInfluenceAllianceImpossibleMod: float
    LoseInfluenceAllianceUnlikelyMod: float
    GainInfluenceSeizeOpeningMod: float
    PoorMod: float
    RichMod: float
    FloodedMod: float
    MinimumAcquireValueEarly: float
    MinimumAcquireValueMid: float
    MinimumAcquireValueLate: float
    SolariNormalThreshold: float
    SolariRichThreshold: float
    SolariFloodedThreshold: float
    SpiceNormalThreshold: float
    SpiceRichThreshold: float
    SpiceFloodedThreshold: float
    WaterNormalThreshold: float
    WaterRichThreshold: float
    WaterFloodedThreshold: float
    TroopNormalThreshold: float
    TroopRichThreshold: float
    TroopFloodedThreshold: float
    ConflictAverageValue: float
    ConflictInterestGarrisonUnitValue: float
    ConflictInterestOpponentsWithAgentsPenalty: float
    ConflictInterestHandSwordValue: float
    ConflictInterestIntrigueSwordValue: float
    ConflictInterestHeighlinerPotential: float
    ConflictPostureNoCompetitorsLowerBound: float
    ConflictPostureNoCompetitorsUpperBound: float
    ConflictPostureSomeCompetitorsLowerBound: float
    ConflictPostureSomeCompetitorsUpperBound: float
    ConflictPostureManyCompetitorsLowerBound: float
    ConflictPostureManyCompetitorsUpperBound: float
    ConflictPostureManyCompetitorsLowerBoundClimax: float
    ConflictPostureManyCompetitorsUpperBoundClimax: float
    ConflictPostureMidMod: float
    ConflictPostureHighMod: float
    CardPlayValueRevealPenalty: float
    OpulenceRevealBonus: float
    OtherMemoryPlayBonusMod: float
    SardaukarLegionRevealBonus: float
    KwisatzHaderachDelayPenalty: float
    LietKynesFremenRevealBonus: float
    TestOfHumanityRelevantOpponentMod: float
    TheVoiceBlockHeighlinerBonus: float
    GuildAmbassadorRevealBonus: float
    GunThopterTroopRevealBonus: float
    GurneyHalleckRevealBonus: float
    WormRidersInfluenceRevealBonus: float
    WormRidersAllianceRevealBonus: float
    DukeLetoAtreidesSpiceValueMod: float
    DukeLetoAtreidesPrudentDiplomacyInfluenceValueThreshold: float
    BaronVladimirHarkonnenGetTroopsBonus: float
    GlossuRabbanInfluenceValueBonus: float
    GlossuRabbanTroopsValueMod: float
    EarlMemnonThorvaldHighCouncilValueBonus: float
    EarlMemnonThorvaldSpiceValueMod: float
    CountessArianaThorvaldWaterValueMod: float
    BriberyInfluenceThreshold: float
    CalculatedHireMentatValueMod: float
    CharismaBuyGainsThreshold: float
    ChoamSharesSolariMod: float
    CouncilorsDispensationSpiceThreshold: float
    DemandRespectConflictMod: float
    GainInfluenceValueThreshold: float
    PlansWithinPlansEarlyInfluenceMod: float
    PlansWithinPlansMeetRequisiteInfluenceMod: float
    PrivateArmySpiceMod: float
    RapidMobilizationDeployMod: float
    RapidMobilizationTroopMod: float
    RecruitmentMissionBuyGainsThreshold: float
    ReinforcementsConflictInterestBonus: float
    StagedIncidentDeployedTroopThreshold: float
    StagedIncidentTotalTroopThreshold: float
    StagedIncidentDeployMod: float
    StagedIncidentTroopMod: float
    TheSleeperMustAwakenSpiceMod: float
    UrgentMissionMentatValueMod: float
    WaterPeddlersUnionWaterThreshold: float
    WindfallSolariThreshold: float
    WindfallSwordmasterThreshold: float
    WindfallChoamSharesThreshold: float
    SpiceRefineryLowSolariValueThreshold: float
    ExpectedStrengthHeighlinerPotential: int
    PotentialStrengthHeighlinerPotential: int
    SeekAlliesValueMod: float
    IntrigueNormalThreshold: float
    IntrigueRichThreshold: float
    IntrigueFloodedThreshold: float
    ResearchValueEarly: float
    ResearchValueMid: float
    ResearchValueLate: float
    ResearchStepValueSingleHelixMod: float
    ResearchStepValueDoubleHelixMod: float
    ResearchTrackSpace17NoBadIntrigueMod: float
    ResearchTrackSpace21ThirdSpaceMod: float
    SpecimenValueEarly: float
    SpecimenValueMid: float
    SpecimenValueLate: float
    SpecimenNormalThreshold: float
    SpecimenRichThreshold: float
    SpecimenFloodedThreshold: float
    SpecimenGoodTleilaxuThreshold: float
    SpecimenGoodTleilaxuBonus: float
    TleilaxuValueEarly: float
    TleilaxuValueMid: float
    TleilaxuValueLate: float
    TleilaxuTrackIntrigue: float
    TleilaxuTrackVP: float
    TleilaxuTrackLateGameMod: float
    TrashIntrigueValue: float
    TwistedMentatBonus: float
    TleilaxuGoodCardThreshold: float
    AcquireTleilaxuReserveThreshold: float
    AcquireTleilaxuReservePenalty: float
    GraftFewRemainingSpaceTargetsPenalty: float
    GraftBothCardsHaveGraftPenalty: float
    GraftAgentIconsPenalty: float
    TleilaxuShadowSynergyMod: float
    TleilaxuHelixSynergyBonus: float
    TleilaxuDoubleHelixSynergyBonus: float
    TleilaxuGraftSynergyBonus: float
    TleilaxuHighCostCardsSynergyMod: float
    TleilaxuSwordmasterSynergyBonus: float
    TleilaxuSligFarmerCardCountOffset: float
    TleilaxuSligFarmerCardCountMod: float
    TleilaxuReclaimForcesLateGameBonus: float
    TleilaxuReclaimForcesNotLateGameMod: float
    TleilaxuReclaimForcesVPBonus: float
    ChairdogGraftRevealMod: float
    DissectingKitCardCostMod: float
    TleilaxuPuppetHighCouncilMod: float
    EconomicPositioningSolariMod: float
    EconomicPositioningDeploySolariThreshold: float
    EconomicPositioningDeployMod: float
    ReplacementEyesTrashValueMod: float
    ShadoutMapesRevealValue: float
    HighPriorityTravelAgentMod: float
    ReplacementEyesAgentMod: float
    SynergyWantsGraftMod: float
    SynergyGraftMod: float
    SynergyHelixMod: float
    SynergyDoubleHelixMod: float
    ImperiumCeremonyMod: float
    StillsuitManufacturerMod: float
    PoliticsPayoffMod: float
    DiscardEnablerMod: float
    DiscardIncentiveMod: float
    DiscardEarly: float
    DiscardMid: float
    DiscardLate: float
    DreadnoughtEarly: float
    DreadnoughtMid: float
    DreadnoughtLate: float
    NegotiateTechEarlyMod: float
    NegotiateTechMidMod: float
    NegotiateTechLateMod: float
    FreighterEarly: float
    FreighterMid: float
    FreighterLate: float
    BuyTechEarly: float
    BuyTechMid: float
    BuyTechLate: float
    ConflictInterestGarrisonDreadnoughtValue: float
    WeirdingWayValue: float
    ImmediacyModValue: float
    CourtIntrigueValue: float
    InTheShadowsTrashValueMod: float
    InTheShadowsTrashValueModBG: float
    FreighterFleetTrashValueMod: float
    IxGuildCompactTrashValueMod: float
    TreacheryTrashValueMod: float
    ConvincingArgumentTrashValueMod: float
    NegotiatedWithdrawalRetreatValue: float
    NegotiatedWithdrawalDeployValueMod: float
    DesertAmbushValue: float
    DesertAmbushNoOppositionPenalty: float
    ImperialBasharSwordValue: float
    IxianEngineerValue: float
    CoordinationValue: float
    ConscriptBeforeLateValue: float
    HeavyLasgunCannonsValue: float
    TessiaVerniusInfluenceMod: float
    SpacingGuildRiseOfIxBonus: float
    QuidProQuoSpiceMod: float
    SecretForcesMod: float
    DiversionTroopMod: float
    AdvancedWeaponrySolariMod: float
    GrandConspiracyDreadnoughtMod: float
    GrandConspiracyHighCouncilMod: float
    GrandConspiracyTSMFMod: float
    GrandConspiracyInfluenceMod: float
    MachineCultureSpiceMod: float
    MachineCultureTechValueMod: float
    WarChestSolariMod: float
    ArtilleryRevealMod: float
    ArtilleryAcquireMod: float
    ArtilleryValueMod: float
    MemocordersInfluenceMod: float
    MemocordersValue3Mod: float
    MemocordersValue2Mod: float
    MemocordersValueConditionalMod: float
    SonicSnoopersIntrigueMod: float
    SonicSnoopersBadValueMod: float
    SonicSnoopersGoodValueMod: float
    TroopTransportsValueMod: float
    HoloprojectorsAcquireMod: float
    HoloprojectorsValueMod: float
    TrainingDronesTroopMod: float
    DetonationDevicesDreadnoughtMod: float
    DetonationDevicesValueMod: float
    DetonationDevicesValueNoDreadnoughtMod: float
    SpySatellitesSpiceMod: float
    SpySatellitesValueLateMod: float
    SpySatellitesValueMidMod: float
    SpySatellitesValueEarlyMod: float
    SpySatellitesValueFinalRoundMod: float
    RestrictedOrdnanceHighCouncilMod: float
    RestrictedOrdnanceValueMod: float
    InvasionShipsAcquireMod: float
    InvasionShipsValueMod: float
    ShuttleFleetSolariMod: float
    HoltzmanEngineAcquirePersuasion0Mod: float
    HoltzmanEngineAcquirePersuasion2Mod: float
    HoltzmanEngineAcquireTSMFMod: float
    HoltzmanEngineValueTSMFMod: float
    FlagshipSolariMod: float
    FlagshipTroopMod: float
    FlagshipValueMod: float
    OverpoweringDreadResourceMod: float
    OverpoweringDreadDeployMod: float
    SpyValueEarly: float
    SpyValueMid: float
    SpyValueLate: float
    ContractValueEarly: float
    ContractValueMid: float
    ContractValueLate: float
    SandwormValueEarly: float
    SandwormValueMid: float
    SandwormValueLate: float
    MakerHooksValueEarly: float
    MakerHooksValueMid: float
    MakerHooksValueLate: float
    RecallAgentValueEarly: float
    RecallAgentValueMid: float
    RecallAgentValueLate: float
    BlowWallValueEarly: float
    BlowWallValueMid: float
    BlowWallValueLate: float
    BattleIconValueEarly: float
    BattleIconValueMid: float
    BattleIconValueLate: float
    SpyRecallMod: float
    ContractMod: float
    WallModWaterMod: float
    WallModSpaceMod: float
    WallModHooksMod: float
    ChaniCleverTacticianDeployMod: float
    CovertOperationMod: float
    DoubleAgentMod: float
    LongLiveTheFightersMod: float
    ReliableInformantMod: float
    ArrakisInformantMod: float
    WeirdingWomanMod: float
    SpaceContractRewardValueModRatio: float
    SpaceContractAgentIconsModRatio: float
    SpaceContractResourceModRatio: float
    SpaceContractSpyModRatio: float
    SpaceContractOtherModRatio: float
    HarvestContractRewardValueModRatio: float
    HarvestContractResourceModRatio: float
    HarvestContractBonusSpiceModRatio: float
    AcquireContractRewardValueModRatio: float
    AcquireContractHighCouncilModRatio: float
    AcquireContractRoundModRatio: float
    PostValueMatchingAgentIcon: float
    PostValueFactionSpace: float
    PostValueFactionSpaceHighValue: float
    PostValueFactionSpaceGuildSpy: float
    PostValueSwordmaster: float
    PostValueInterstellarShipping: float
    PostValueHaggaBasin: float
    PostValueSietchTabr: float
    PostValueUnseenNetwork: float
    MuadDibFremenMod: float
    MuadDibMakerHooksMod: float
    LadyMargoFenringBeneGesseritSpiceMod: float
    LadyAmberMetulliInfluenceMod: float
    LadyJessicaSpiceAgonyMod: float
    LadyJessicaOtherMemoriesMod: float
    PrincessIrulanEmperorMod: float
    StabanTuekUnseenNetworkMod: float
    StabanTuekIconMod: float
    StabanTuekPostMod: float
    ShaddamCorrinoIVSignetHigh: float
    ShaddamCorrinoIVSignetMid: float
    SynergyTSMFUprisingMod: float
    SynergySpyMod: float
    SynergySpyCardMod: float
    SynergyContractCompleted: float
    SynergyContractCompletedMax: float
    SynergyContractOpen: float
    SynergyContractOpenMax: float
    SynergyHaveHooksMod: float
    SynergyHooksFremenInfluenceMod: float
    ConflictInterestWormPotential: float
    ExpectedStrengthWormPotentialA: int
    ExpectedStrengthWormPotentialB: int
    PotentialStrengthWormPotential: int
    MatchModWildcard: float
    MatchModStandard: float
    BuyAccessSolariMod: float
    CallToArmsAcquireMod: float
    CouncilorsAmbitionMod: float
    DepartForArrakisSGMod: float
    DetonationHooksMod: float
    DetonationBlowWallMod: float
    DetonationSandWormMod: float
    DevourHooksMod: float
    DevourSandWormMod: float
    ImperiumPoliticsInfluenceThreshold: float
    InspireAweHooksMod: float
    InspireAweSandWormMod: float
    MarketOpportunitySpiceMod: float
    MarketOpportunitySolariMod: float
    MercenariesSolariMod: float
    ShaddamsFavorEmperorMod: float
    ShadowAllianceMod: float
    SpecialMissionHooksMod: float
    SpecialMissionSandWormMod: float
    StrategicStockpilingSpiceMod: float
    StrategicStockpilingWaterMod: float
    StrategicStockpilingInfluenceMod: float
    UnexpectedAlliesWaterMod: float
    UnexpectedAlliesHooksMod: float
    WeirdingCombatInfluenceMod: float
    SpaceSpyUseInfiltrate3SpiesMod: float
    SpaceSpyUseIntelligenceMod: float
    MakerHooksFremenMod: float
    WantSpyImperiumMod: float
    SpringTheTrapSpyMod: float
    SpyInfiltrateBoardSpaceValueMod: float
    HooksModHalfOfOpponents: float
    HooksModAllOpponents: float
    WaterHooksMod: float


HARD: Final = AIConstants(
    VictoryPointValueEarly=6.0,
    VictoryPointValueMid=6.0,
    VictoryPointValueLate=9.0,
    PersuasionValueEarly=1.0,
    PersuasionValueMid=0.75,
    PersuasionValueLate=0.66,
    StrengthValueEarly=0.66,
    StrengthValueMid=0.5,
    StrengthValueLate=0.5,
    SolariValueEarly=0.65,
    SolariValueMid=0.5,
    SolariValueLate=0.25,
    SolariMissingHighCouncilMod=1.1,
    SolariMissingSwordmasterMod=1.6,
    SpiceValueEarly=2.0,
    SpiceValueMid=1.5,
    SpiceValueLate=1.5,
    BonusSpiceMod=1.25,
    WaterValueEarly=2.25,
    WaterValueMid=1.8,
    WaterValueLate=1.3,
    TroopValueEarly=1.25,
    TroopValueMid=1.25,
    TroopValueLate=1.25,
    IntrigueValueEarly=2.25,
    IntrigueValueMid=2.5,
    IntrigueValueLate=2.75,
    IntrigueStealBonus=1.0,
    CardDrawValue=1.5,
    TrashCardEarly=2.75,
    TrashCardMid=2.0,
    TrashCardLate=1.0,
    DeployEarly=0.75,
    DeployMid=0.75,
    DeployLate=1.25,
    SolariShortValue=0.7,
    SpiceShortAmount=3.0,
    TroopShortAmount=2.0,
    WaterShortAmount=3.0,
    AcquireNewIconsBonus=0.45,
    ConsolidationValueMod=-0.55,
    SynergyModMaxValue=2.0,
    SynergyTSMFCardValue=2.0,
    SynergyTSMFHighPersuasionValue=0.5,
    SynergyFremenWithBondInDeck=0.5,
    SynergyBondWithFremenInDeck=0.66,
    SynergyBeneGesseritWithBondInDeck=0.75,
    SynergyWithFactionInDeck=0.5,
    GainSwordmasterEarly=50.0,
    GainSwordmasterMid=50.0,
    GainSwordmasterLate=10.0,
    GainHighCouncilEarly=15.0,
    GainHighCouncilMid=9.0,
    GainHighCouncilLate=5.0,
    GainFoldspaceEarly=3.0,
    GainFoldspaceMid=1.5,
    GainFoldspaceLate=0.5,
    GainMentatEarly=2.25,
    GainMentatMid=3.5,
    GainMentatLate=4.5,
    SellMelangeLowSolariValueThreshold=0.5,
    SellMelangeMidSolariValueThreshold=0.75,
    SellMelangeHighSolariValueThreshold=1.0,
    SellMelangeSpaceBonus=2.0,
    ConspireSpaceBonus=2.0,
    HeighlinerSpaceBonus=4.0,
    HeighlinerSpaceLowSupplyPenalty=-6.0,
    HeighlinerSpaceEarlyInRoundPenalty=-3.0,
    ControlSolariEarly=4.0,
    ControlSolariMid=1.75,
    ControlSolariLate=0.33,
    ControlSpiceEarly=6.0,
    ControlSpiceMid=3.0,
    ControlSpiceLate=1.0,
    InfluenceValue=2.25,
    GainInfluenceDefendAllianceMod=1.5,
    GainInfluenceDefendAllianceThreatenedMod=2.0,
    GainInfluenceVictoryPointMod=1.25,
    GainInfluenceVictoryPointLateMod=1.65,
    GainInfluenceAllianceMod=1.25,
    GainInfluenceAllianceLateMod=1.65,
    GainInfluenceThreatenedAllianceMod=1.75,
    GainInfluenceStealAllianceMod=1.75,
    GainInfluenceStealAllianceEndgameMod=3.0,
    GainInfluenceThreatenAllianceMod=1.3,
    GainInfluenceSecureAllianceMod=0.66,
    GainInfluenceAllianceImpossibleMod=0.25,
    GainInfluenceAllianceUnlikelyMod=0.5,
    GainInfluenceCardAllianceBonusMod=1.25,
    LoseInfluenceForfeitAllianceMod=2.5,
    LoseInfluenceForfeitAllianceCushionMod=1.75,
    LoseInfluenceForfeitVictoryPoint=2.0,
    LoseInfluenceAllianceImpossibleMod=0.25,
    LoseInfluenceAllianceUnlikelyMod=0.33,
    GainInfluenceSeizeOpeningMod=1.2,
    PoorMod=1.25,
    RichMod=0.5,
    FloodedMod=0.25,
    MinimumAcquireValueEarly=1.2,
    MinimumAcquireValueMid=1.7,
    MinimumAcquireValueLate=2.2,
    SolariNormalThreshold=3.0,
    SolariRichThreshold=8.0,
    SolariFloodedThreshold=9.0,
    SpiceNormalThreshold=3.0,
    SpiceRichThreshold=5.0,
    SpiceFloodedThreshold=8.0,
    WaterNormalThreshold=2.0,
    WaterRichThreshold=3.0,
    WaterFloodedThreshold=4.0,
    TroopNormalThreshold=2.0,
    TroopRichThreshold=4.0,
    TroopFloodedThreshold=5.0,
    ConflictAverageValue=14.0,
    ConflictInterestGarrisonUnitValue=2.5,
    ConflictInterestOpponentsWithAgentsPenalty=-1.5,
    ConflictInterestHandSwordValue=1.0,
    ConflictInterestIntrigueSwordValue=0.5,
    ConflictInterestHeighlinerPotential=5.0,
    ConflictPostureNoCompetitorsLowerBound=-10.0,
    ConflictPostureNoCompetitorsUpperBound=5.0,
    ConflictPostureSomeCompetitorsLowerBound=-2.5,
    ConflictPostureSomeCompetitorsUpperBound=12.5,
    ConflictPostureManyCompetitorsLowerBound=5.0,
    ConflictPostureManyCompetitorsUpperBound=20.0,
    ConflictPostureManyCompetitorsLowerBoundClimax=10.0,
    ConflictPostureManyCompetitorsUpperBoundClimax=15.0,
    ConflictPostureMidMod=1.4,
    ConflictPostureHighMod=1.8,
    CardPlayValueRevealPenalty=-0.5,
    OpulenceRevealBonus=5.0,
    OtherMemoryPlayBonusMod=0.66,
    SardaukarLegionRevealBonus=3.0,
    KwisatzHaderachDelayPenalty=-50.0,
    LietKynesFremenRevealBonus=3.0,
    TestOfHumanityRelevantOpponentMod=2.0,
    TheVoiceBlockHeighlinerBonus=2.0,
    GuildAmbassadorRevealBonus=4.0,
    GunThopterTroopRevealBonus=1.0,
    GurneyHalleckRevealBonus=1.5,
    WormRidersInfluenceRevealBonus=4.0,
    WormRidersAllianceRevealBonus=4.0,
    DukeLetoAtreidesSpiceValueMod=1.1,
    DukeLetoAtreidesPrudentDiplomacyInfluenceValueThreshold=2.4,
    BaronVladimirHarkonnenGetTroopsBonus=0.75,
    GlossuRabbanInfluenceValueBonus=0.75,
    GlossuRabbanTroopsValueMod=0.9,
    EarlMemnonThorvaldHighCouncilValueBonus=1.5,
    EarlMemnonThorvaldSpiceValueMod=0.9,
    CountessArianaThorvaldWaterValueMod=0.95,
    BriberyInfluenceThreshold=3.75,
    CalculatedHireMentatValueMod=0.33,
    CharismaBuyGainsThreshold=2.5,
    ChoamSharesSolariMod=1.25,
    CouncilorsDispensationSpiceThreshold=5.0,
    DemandRespectConflictMod=1.2,
    GainInfluenceValueThreshold=3.0,
    PlansWithinPlansEarlyInfluenceMod=1.25,
    PlansWithinPlansMeetRequisiteInfluenceMod=1.5,
    PrivateArmySpiceMod=1.1,
    RapidMobilizationDeployMod=0.5,
    RapidMobilizationTroopMod=1.3,
    RecruitmentMissionBuyGainsThreshold=1.33,
    ReinforcementsConflictInterestBonus=3.0,
    StagedIncidentDeployedTroopThreshold=4.0,
    StagedIncidentTotalTroopThreshold=3.0,
    StagedIncidentDeployMod=1.2,
    StagedIncidentTroopMod=1.2,
    TheSleeperMustAwakenSpiceMod=1.25,
    UrgentMissionMentatValueMod=0.5,
    WaterPeddlersUnionWaterThreshold=1.0,
    WindfallSolariThreshold=3.0,
    WindfallSwordmasterThreshold=8.0,
    WindfallChoamSharesThreshold=5.0,
    SpiceRefineryLowSolariValueThreshold=0.25,
    ExpectedStrengthHeighlinerPotential=7,
    PotentialStrengthHeighlinerPotential=10,
    SeekAlliesValueMod=0.33,
    IntrigueNormalThreshold=1.0,
    IntrigueRichThreshold=2.0,
    IntrigueFloodedThreshold=3.0,
    ResearchValueEarly=2.25,
    ResearchValueMid=2.25,
    ResearchValueLate=2.25,
    ResearchStepValueSingleHelixMod=0.75,
    ResearchStepValueDoubleHelixMod=1.0,
    ResearchTrackSpace17NoBadIntrigueMod=1.0,
    ResearchTrackSpace21ThirdSpaceMod=0.33,
    SpecimenValueEarly=1.0,
    SpecimenValueMid=1.0,
    SpecimenValueLate=0.75,
    SpecimenNormalThreshold=2.0,
    SpecimenRichThreshold=3.0,
    SpecimenFloodedThreshold=4.0,
    SpecimenGoodTleilaxuThreshold=1.5,
    SpecimenGoodTleilaxuBonus=1.0,
    TleilaxuValueEarly=2.25,
    TleilaxuValueMid=2.25,
    TleilaxuValueLate=2.25,
    TleilaxuTrackIntrigue=1.0,
    TleilaxuTrackVP=4.0,
    TleilaxuTrackLateGameMod=0.25,
    TrashIntrigueValue=-1.25,
    TwistedMentatBonus=5.0,
    TleilaxuGoodCardThreshold=3.0,
    AcquireTleilaxuReserveThreshold=1.0,
    AcquireTleilaxuReservePenalty=-5.0,
    GraftFewRemainingSpaceTargetsPenalty=-4.0,
    GraftBothCardsHaveGraftPenalty=-1.5,
    GraftAgentIconsPenalty=-3.0,
    TleilaxuShadowSynergyMod=0.5,
    TleilaxuHelixSynergyBonus=1.5,
    TleilaxuDoubleHelixSynergyBonus=2.0,
    TleilaxuGraftSynergyBonus=0.75,
    TleilaxuHighCostCardsSynergyMod=0.5,
    TleilaxuSwordmasterSynergyBonus=1.0,
    TleilaxuSligFarmerCardCountOffset=2.0,
    TleilaxuSligFarmerCardCountMod=0.5,
    TleilaxuReclaimForcesLateGameBonus=0.5,
    TleilaxuReclaimForcesNotLateGameMod=-0.5,
    TleilaxuReclaimForcesVPBonus=2.0,
    ChairdogGraftRevealMod=0.66,
    DissectingKitCardCostMod=-0.5,
    TleilaxuPuppetHighCouncilMod=1.2,
    EconomicPositioningSolariMod=1.5,
    EconomicPositioningDeploySolariThreshold=0.75,
    EconomicPositioningDeployMod=1.2,
    ReplacementEyesTrashValueMod=1.5,
    ShadoutMapesRevealValue=1.0,
    HighPriorityTravelAgentMod=0.5,
    ReplacementEyesAgentMod=3.5,
    SynergyWantsGraftMod=1.1,
    SynergyGraftMod=1.1,
    SynergyHelixMod=1.2,
    SynergyDoubleHelixMod=1.2,
    ImperiumCeremonyMod=1.33,
    StillsuitManufacturerMod=1.0,
    PoliticsPayoffMod=1.33,
    DiscardEnablerMod=1.1,
    DiscardIncentiveMod=1.1,
    DiscardEarly=-1.0,
    DiscardMid=-1.0,
    DiscardLate=-1.0,
    DreadnoughtEarly=6.0,
    DreadnoughtMid=5.0,
    DreadnoughtLate=3.0,
    NegotiateTechEarlyMod=0.9,
    NegotiateTechMidMod=0.8,
    NegotiateTechLateMod=0.7,
    FreighterEarly=4.2,
    FreighterMid=4.2,
    FreighterLate=4.2,
    BuyTechEarly=1.0,
    BuyTechMid=0.5,
    BuyTechLate=0.0,
    ConflictInterestGarrisonDreadnoughtValue=1.5,
    WeirdingWayValue=1.5,
    ImmediacyModValue=1.5,
    CourtIntrigueValue=2.0,
    InTheShadowsTrashValueMod=1.2,
    InTheShadowsTrashValueModBG=2.0,
    FreighterFleetTrashValueMod=2.1,
    IxGuildCompactTrashValueMod=1.1,
    TreacheryTrashValueMod=1.5,
    ConvincingArgumentTrashValueMod=-0.25,
    NegotiatedWithdrawalRetreatValue=2.5,
    NegotiatedWithdrawalDeployValueMod=1.5,
    DesertAmbushValue=3.0,
    DesertAmbushNoOppositionPenalty=-2.0,
    ImperialBasharSwordValue=0.33,
    IxianEngineerValue=2.0,
    CoordinationValue=1.0,
    ConscriptBeforeLateValue=1.75,
    HeavyLasgunCannonsValue=1.33,
    TessiaVerniusInfluenceMod=1.2,
    SpacingGuildRiseOfIxBonus=1.5,
    QuidProQuoSpiceMod=1.1,
    SecretForcesMod=2.2,
    DiversionTroopMod=2.2,
    AdvancedWeaponrySolariMod=1.2,
    GrandConspiracyDreadnoughtMod=1.33,
    GrandConspiracyHighCouncilMod=1.33,
    GrandConspiracyTSMFMod=1.33,
    GrandConspiracyInfluenceMod=1.5,
    MachineCultureSpiceMod=1.2,
    MachineCultureTechValueMod=1.2,
    WarChestSolariMod=1.5,
    ArtilleryRevealMod=1.66,
    ArtilleryAcquireMod=1.2,
    ArtilleryValueMod=1.1,
    MemocordersInfluenceMod=1.5,
    MemocordersValue3Mod=1.25,
    MemocordersValue2Mod=1.1,
    MemocordersValueConditionalMod=1.33,
    SonicSnoopersIntrigueMod=1.2,
    SonicSnoopersBadValueMod=1.25,
    SonicSnoopersGoodValueMod=1.1,
    TroopTransportsValueMod=1.5,
    HoloprojectorsAcquireMod=1.2,
    HoloprojectorsValueMod=1.2,
    TrainingDronesTroopMod=0.9,
    DetonationDevicesDreadnoughtMod=1.5,
    DetonationDevicesValueMod=1.25,
    DetonationDevicesValueNoDreadnoughtMod=-2.0,
    SpySatellitesSpiceMod=1.1,
    SpySatellitesValueLateMod=1.5,
    SpySatellitesValueMidMod=1.25,
    SpySatellitesValueEarlyMod=1.1,
    SpySatellitesValueFinalRoundMod=1.25,
    RestrictedOrdnanceHighCouncilMod=1.5,
    RestrictedOrdnanceValueMod=1.33,
    InvasionShipsAcquireMod=1.2,
    InvasionShipsValueMod=1.2,
    ShuttleFleetSolariMod=0.66,
    HoltzmanEngineAcquirePersuasion0Mod=0.75,
    HoltzmanEngineAcquirePersuasion2Mod=1.25,
    HoltzmanEngineAcquireTSMFMod=1.33,
    HoltzmanEngineValueTSMFMod=1.5,
    FlagshipSolariMod=1.5,
    FlagshipTroopMod=0.75,
    FlagshipValueMod=1.25,
    OverpoweringDreadResourceMod=2.0,
    OverpoweringDreadDeployMod=2.0,
    SpyValueEarly=1.66,
    SpyValueMid=1.66,
    SpyValueLate=1.33,
    ContractValueEarly=2.0,
    ContractValueMid=1.75,
    ContractValueLate=1.5,
    SandwormValueEarly=3.0,
    SandwormValueMid=3.0,
    SandwormValueLate=3.0,
    MakerHooksValueEarly=5.0,
    MakerHooksValueMid=4.0,
    MakerHooksValueLate=3.0,
    RecallAgentValueEarly=5.0,
    RecallAgentValueMid=5.0,
    RecallAgentValueLate=5.0,
    BlowWallValueEarly=0.0,
    BlowWallValueMid=0.0,
    BlowWallValueLate=0.0,
    BattleIconValueEarly=2.5,
    BattleIconValueMid=2.5,
    BattleIconValueLate=4.5,
    SpyRecallMod=4.5,
    ContractMod=0.33,
    WallModWaterMod=0.66,
    WallModSpaceMod=1.0,
    WallModHooksMod=1.5,
    ChaniCleverTacticianDeployMod=1.33,
    CovertOperationMod=2.5,
    DoubleAgentMod=0.5,
    LongLiveTheFightersMod=2.0,
    ReliableInformantMod=0.66,
    ArrakisInformantMod=0.66,
    WeirdingWomanMod=0.5,
    SpaceContractRewardValueModRatio=0.5,
    SpaceContractAgentIconsModRatio=0.17,
    SpaceContractResourceModRatio=0.16,
    SpaceContractSpyModRatio=0.16,
    SpaceContractOtherModRatio=0.17,
    HarvestContractRewardValueModRatio=0.5,
    HarvestContractResourceModRatio=0.33,
    HarvestContractBonusSpiceModRatio=0.33,
    AcquireContractRewardValueModRatio=0.34,
    AcquireContractHighCouncilModRatio=0.33,
    AcquireContractRoundModRatio=0.33,
    PostValueMatchingAgentIcon=1.0,
    PostValueFactionSpace=2.0,
    PostValueFactionSpaceHighValue=1.0,
    PostValueFactionSpaceGuildSpy=2.0,
    PostValueSwordmaster=2.0,
    PostValueInterstellarShipping=3.0,
    PostValueHaggaBasin=1.5,
    PostValueSietchTabr=1.5,
    PostValueUnseenNetwork=1.0,
    MuadDibFremenMod=1.25,
    MuadDibMakerHooksMod=1.33,
    LadyMargoFenringBeneGesseritSpiceMod=0.75,
    LadyAmberMetulliInfluenceMod=0.75,
    LadyJessicaSpiceAgonyMod=0.5,
    LadyJessicaOtherMemoriesMod=1.5,
    PrincessIrulanEmperorMod=1.0,
    StabanTuekUnseenNetworkMod=1.0,
    StabanTuekIconMod=1.2,
    StabanTuekPostMod=2.5,
    ShaddamCorrinoIVSignetHigh=-2.0,
    ShaddamCorrinoIVSignetMid=-1.0,
    SynergyTSMFUprisingMod=5.0,
    SynergySpyMod=0.5,
    SynergySpyCardMod=0.25,
    SynergyContractCompleted=0.75,
    SynergyContractCompletedMax=3.0,
    SynergyContractOpen=0.5,
    SynergyContractOpenMax=1.5,
    SynergyHaveHooksMod=1.5,
    SynergyHooksFremenInfluenceMod=1.0,
    ConflictInterestWormPotential=3.0,
    ExpectedStrengthWormPotentialA=2,
    ExpectedStrengthWormPotentialB=5,
    PotentialStrengthWormPotential=2,
    MatchModWildcard=1.5,
    MatchModStandard=2.0,
    BuyAccessSolariMod=1.2,
    CallToArmsAcquireMod=0.5,
    CouncilorsAmbitionMod=3.0,
    DepartForArrakisSGMod=0.25,
    DetonationHooksMod=1.3,
    DetonationBlowWallMod=0.33,
    DetonationSandWormMod=4.0,
    DevourHooksMod=1.1,
    DevourSandWormMod=1.1,
    ImperiumPoliticsInfluenceThreshold=3.0,
    InspireAweHooksMod=1.1,
    InspireAweSandWormMod=1.1,
    MarketOpportunitySpiceMod=1.1,
    MarketOpportunitySolariMod=1.2,
    MercenariesSolariMod=1.1,
    ShaddamsFavorEmperorMod=0.25,
    ShadowAllianceMod=1.2,
    SpecialMissionHooksMod=1.2,
    SpecialMissionSandWormMod=4.0,
    StrategicStockpilingSpiceMod=1.2,
    StrategicStockpilingWaterMod=1.2,
    StrategicStockpilingInfluenceMod=0.25,
    UnexpectedAlliesWaterMod=1.2,
    UnexpectedAlliesHooksMod=1.1,
    WeirdingCombatInfluenceMod=0.25,
    SpaceSpyUseInfiltrate3SpiesMod=0.5,
    SpaceSpyUseIntelligenceMod=1.25,
    MakerHooksFremenMod=1.2,
    WantSpyImperiumMod=1.15,
    SpringTheTrapSpyMod=1.5,
    SpyInfiltrateBoardSpaceValueMod=0.33,
    HooksModHalfOfOpponents=0.5,
    HooksModAllOpponents=0.5,
    WaterHooksMod=1.25,
)


MEDIUM: Final = AIConstants(
    VictoryPointValueEarly=6.0,
    VictoryPointValueMid=6.0,
    VictoryPointValueLate=9.0,
    PersuasionValueEarly=1.0,
    PersuasionValueMid=0.75,
    PersuasionValueLate=0.66,
    StrengthValueEarly=0.66,
    StrengthValueMid=0.5,
    StrengthValueLate=0.5,
    SolariValueEarly=0.65,
    SolariValueMid=0.5,
    SolariValueLate=0.25,
    SolariMissingHighCouncilMod=1.0,
    SolariMissingSwordmasterMod=1.0,
    SpiceValueEarly=2.0,
    SpiceValueMid=1.5,
    SpiceValueLate=1.5,
    BonusSpiceMod=1.25,
    WaterValueEarly=2.25,
    WaterValueMid=1.8,
    WaterValueLate=1.3,
    TroopValueEarly=1.25,
    TroopValueMid=1.25,
    TroopValueLate=1.25,
    IntrigueValueEarly=2.25,
    IntrigueValueMid=2.5,
    IntrigueValueLate=2.75,
    IntrigueStealBonus=1.0,
    CardDrawValue=1.5,
    TrashCardEarly=2.75,
    TrashCardMid=2.0,
    TrashCardLate=1.0,
    DeployEarly=0.75,
    DeployMid=0.75,
    DeployLate=1.25,
    SolariShortValue=0.7,
    SpiceShortAmount=3.0,
    TroopShortAmount=2.0,
    WaterShortAmount=3.0,
    AcquireNewIconsBonus=0.1,
    ConsolidationValueMod=-0.25,
    SynergyModMaxValue=2.0,
    SynergyTSMFCardValue=2.0,
    SynergyTSMFHighPersuasionValue=0.5,
    SynergyFremenWithBondInDeck=0.5,
    SynergyBondWithFremenInDeck=0.66,
    SynergyBeneGesseritWithBondInDeck=0.75,
    SynergyWithFactionInDeck=0.5,
    GainSwordmasterEarly=50.0,
    GainSwordmasterMid=50.0,
    GainSwordmasterLate=10.0,
    GainHighCouncilEarly=15.0,
    GainHighCouncilMid=9.0,
    GainHighCouncilLate=5.0,
    GainFoldspaceEarly=3.0,
    GainFoldspaceMid=1.5,
    GainFoldspaceLate=0.5,
    GainMentatEarly=2.25,
    GainMentatMid=3.5,
    GainMentatLate=4.5,
    SellMelangeLowSolariValueThreshold=0.5,
    SellMelangeMidSolariValueThreshold=0.75,
    SellMelangeHighSolariValueThreshold=1.0,
    SellMelangeSpaceBonus=2.0,
    ConspireSpaceBonus=2.0,
    HeighlinerSpaceBonus=4.0,
    HeighlinerSpaceLowSupplyPenalty=-6.0,
    HeighlinerSpaceEarlyInRoundPenalty=-3.0,
    ControlSolariEarly=4.0,
    ControlSolariMid=1.75,
    ControlSolariLate=0.33,
    ControlSpiceEarly=6.0,
    ControlSpiceMid=3.0,
    ControlSpiceLate=1.0,
    InfluenceValue=2.25,
    GainInfluenceDefendAllianceMod=1.15,
    GainInfluenceDefendAllianceThreatenedMod=1.33,
    GainInfluenceVictoryPointMod=1.05,
    GainInfluenceVictoryPointLateMod=1.65,
    GainInfluenceAllianceMod=1.15,
    GainInfluenceAllianceLateMod=1.65,
    GainInfluenceThreatenedAllianceMod=1.25,
    GainInfluenceStealAllianceMod=1.25,
    GainInfluenceStealAllianceEndgameMod=3.0,
    GainInfluenceThreatenAllianceMod=1.05,
    GainInfluenceSecureAllianceMod=0.9,
    GainInfluenceAllianceImpossibleMod=0.7,
    GainInfluenceAllianceUnlikelyMod=0.85,
    GainInfluenceCardAllianceBonusMod=1.05,
    LoseInfluenceForfeitAllianceMod=1.6,
    LoseInfluenceForfeitAllianceCushionMod=1.2,
    LoseInfluenceForfeitVictoryPoint=1.33,
    LoseInfluenceAllianceImpossibleMod=0.7,
    LoseInfluenceAllianceUnlikelyMod=0.8,
    GainInfluenceSeizeOpeningMod=1.0,
    PoorMod=1.05,
    RichMod=1.0,
    FloodedMod=0.85,
    MinimumAcquireValueEarly=0.7,
    MinimumAcquireValueMid=0.75,
    MinimumAcquireValueLate=0.75,
    SolariNormalThreshold=3.0,
    SolariRichThreshold=8.0,
    SolariFloodedThreshold=9.0,
    SpiceNormalThreshold=3.0,
    SpiceRichThreshold=5.0,
    SpiceFloodedThreshold=8.0,
    WaterNormalThreshold=2.0,
    WaterRichThreshold=3.0,
    WaterFloodedThreshold=4.0,
    TroopNormalThreshold=2.0,
    TroopRichThreshold=4.0,
    TroopFloodedThreshold=5.0,
    ConflictAverageValue=14.0,
    ConflictInterestGarrisonUnitValue=2.5,
    ConflictInterestOpponentsWithAgentsPenalty=-1.5,
    ConflictInterestHandSwordValue=1.0,
    ConflictInterestIntrigueSwordValue=0.5,
    ConflictInterestHeighlinerPotential=5.0,
    ConflictPostureNoCompetitorsLowerBound=-10.0,
    ConflictPostureNoCompetitorsUpperBound=5.0,
    ConflictPostureSomeCompetitorsLowerBound=-2.5,
    ConflictPostureSomeCompetitorsUpperBound=12.5,
    ConflictPostureManyCompetitorsLowerBound=5.0,
    ConflictPostureManyCompetitorsUpperBound=20.0,
    ConflictPostureManyCompetitorsLowerBoundClimax=10.0,
    ConflictPostureManyCompetitorsUpperBoundClimax=15.0,
    ConflictPostureMidMod=1.0,
    ConflictPostureHighMod=1.05,
    CardPlayValueRevealPenalty=-0.5,
    OpulenceRevealBonus=5.0,
    OtherMemoryPlayBonusMod=0.66,
    SardaukarLegionRevealBonus=3.0,
    KwisatzHaderachDelayPenalty=-50.0,
    LietKynesFremenRevealBonus=3.0,
    TestOfHumanityRelevantOpponentMod=2.0,
    TheVoiceBlockHeighlinerBonus=2.0,
    GuildAmbassadorRevealBonus=4.0,
    GunThopterTroopRevealBonus=1.0,
    GurneyHalleckRevealBonus=1.5,
    WormRidersInfluenceRevealBonus=4.0,
    WormRidersAllianceRevealBonus=4.0,
    DukeLetoAtreidesSpiceValueMod=1.1,
    DukeLetoAtreidesPrudentDiplomacyInfluenceValueThreshold=2.4,
    BaronVladimirHarkonnenGetTroopsBonus=0.75,
    GlossuRabbanInfluenceValueBonus=0.75,
    GlossuRabbanTroopsValueMod=0.9,
    EarlMemnonThorvaldHighCouncilValueBonus=1.5,
    EarlMemnonThorvaldSpiceValueMod=0.9,
    CountessArianaThorvaldWaterValueMod=0.95,
    BriberyInfluenceThreshold=3.75,
    CalculatedHireMentatValueMod=0.33,
    CharismaBuyGainsThreshold=2.5,
    ChoamSharesSolariMod=1.25,
    CouncilorsDispensationSpiceThreshold=5.0,
    DemandRespectConflictMod=1.2,
    GainInfluenceValueThreshold=3.0,
    PlansWithinPlansEarlyInfluenceMod=1.25,
    PlansWithinPlansMeetRequisiteInfluenceMod=1.5,
    PrivateArmySpiceMod=1.1,
    RapidMobilizationDeployMod=0.5,
    RapidMobilizationTroopMod=1.3,
    RecruitmentMissionBuyGainsThreshold=1.33,
    ReinforcementsConflictInterestBonus=3.0,
    StagedIncidentDeployedTroopThreshold=4.0,
    StagedIncidentTotalTroopThreshold=3.0,
    StagedIncidentDeployMod=1.2,
    StagedIncidentTroopMod=1.2,
    TheSleeperMustAwakenSpiceMod=1.25,
    UrgentMissionMentatValueMod=0.5,
    WaterPeddlersUnionWaterThreshold=1.0,
    WindfallSolariThreshold=3.0,
    WindfallSwordmasterThreshold=8.0,
    WindfallChoamSharesThreshold=5.0,
    SpiceRefineryLowSolariValueThreshold=0.25,
    ExpectedStrengthHeighlinerPotential=7,
    PotentialStrengthHeighlinerPotential=10,
    SeekAlliesValueMod=0.33,
    IntrigueNormalThreshold=1.0,
    IntrigueRichThreshold=2.0,
    IntrigueFloodedThreshold=3.0,
    ResearchValueEarly=2.25,
    ResearchValueMid=2.25,
    ResearchValueLate=2.25,
    ResearchStepValueSingleHelixMod=0.75,
    ResearchStepValueDoubleHelixMod=1.0,
    ResearchTrackSpace17NoBadIntrigueMod=1.0,
    ResearchTrackSpace21ThirdSpaceMod=0.33,
    SpecimenValueEarly=1.0,
    SpecimenValueMid=1.0,
    SpecimenValueLate=0.75,
    SpecimenNormalThreshold=2.0,
    SpecimenRichThreshold=3.0,
    SpecimenFloodedThreshold=4.0,
    SpecimenGoodTleilaxuThreshold=1.5,
    SpecimenGoodTleilaxuBonus=1.0,
    TleilaxuValueEarly=2.25,
    TleilaxuValueMid=2.25,
    TleilaxuValueLate=2.25,
    TleilaxuTrackIntrigue=1.0,
    TleilaxuTrackVP=4.0,
    TleilaxuTrackLateGameMod=0.25,
    TrashIntrigueValue=-1.25,
    TwistedMentatBonus=5.0,
    TleilaxuGoodCardThreshold=3.0,
    AcquireTleilaxuReserveThreshold=1.0,
    AcquireTleilaxuReservePenalty=-5.0,
    GraftFewRemainingSpaceTargetsPenalty=-4.0,
    GraftBothCardsHaveGraftPenalty=-1.5,
    GraftAgentIconsPenalty=-3.0,
    TleilaxuShadowSynergyMod=0.5,
    TleilaxuHelixSynergyBonus=1.5,
    TleilaxuDoubleHelixSynergyBonus=2.0,
    TleilaxuGraftSynergyBonus=0.75,
    TleilaxuHighCostCardsSynergyMod=0.5,
    TleilaxuSwordmasterSynergyBonus=1.0,
    TleilaxuSligFarmerCardCountOffset=2.0,
    TleilaxuSligFarmerCardCountMod=0.5,
    TleilaxuReclaimForcesLateGameBonus=0.5,
    TleilaxuReclaimForcesNotLateGameMod=-0.5,
    TleilaxuReclaimForcesVPBonus=2.0,
    ChairdogGraftRevealMod=0.66,
    DissectingKitCardCostMod=-0.5,
    TleilaxuPuppetHighCouncilMod=1.2,
    EconomicPositioningSolariMod=1.5,
    EconomicPositioningDeploySolariThreshold=0.75,
    EconomicPositioningDeployMod=1.2,
    ReplacementEyesTrashValueMod=1.5,
    ShadoutMapesRevealValue=1.0,
    HighPriorityTravelAgentMod=0.5,
    ReplacementEyesAgentMod=3.5,
    SynergyWantsGraftMod=1.1,
    SynergyGraftMod=1.1,
    SynergyHelixMod=1.2,
    SynergyDoubleHelixMod=1.2,
    ImperiumCeremonyMod=1.33,
    StillsuitManufacturerMod=1.0,
    PoliticsPayoffMod=1.33,
    DiscardEnablerMod=1.1,
    DiscardIncentiveMod=1.1,
    DiscardEarly=-1.0,
    DiscardMid=-1.0,
    DiscardLate=-1.0,
    DreadnoughtEarly=6.0,
    DreadnoughtMid=5.0,
    DreadnoughtLate=3.0,
    NegotiateTechEarlyMod=0.9,
    NegotiateTechMidMod=0.8,
    NegotiateTechLateMod=0.7,
    FreighterEarly=4.2,
    FreighterMid=4.2,
    FreighterLate=4.2,
    BuyTechEarly=1.0,
    BuyTechMid=0.5,
    BuyTechLate=0.0,
    ConflictInterestGarrisonDreadnoughtValue=1.5,
    WeirdingWayValue=1.5,
    ImmediacyModValue=1.5,
    CourtIntrigueValue=2.0,
    InTheShadowsTrashValueMod=1.2,
    InTheShadowsTrashValueModBG=2.0,
    FreighterFleetTrashValueMod=2.1,
    IxGuildCompactTrashValueMod=1.1,
    TreacheryTrashValueMod=1.5,
    ConvincingArgumentTrashValueMod=-0.25,
    NegotiatedWithdrawalRetreatValue=2.5,
    NegotiatedWithdrawalDeployValueMod=1.5,
    DesertAmbushValue=3.0,
    DesertAmbushNoOppositionPenalty=-2.0,
    ImperialBasharSwordValue=0.33,
    IxianEngineerValue=2.0,
    CoordinationValue=1.0,
    ConscriptBeforeLateValue=1.75,
    HeavyLasgunCannonsValue=1.33,
    TessiaVerniusInfluenceMod=1.2,
    SpacingGuildRiseOfIxBonus=1.5,
    QuidProQuoSpiceMod=1.1,
    SecretForcesMod=2.2,
    DiversionTroopMod=2.2,
    AdvancedWeaponrySolariMod=1.2,
    GrandConspiracyDreadnoughtMod=1.33,
    GrandConspiracyHighCouncilMod=1.33,
    GrandConspiracyTSMFMod=1.33,
    GrandConspiracyInfluenceMod=1.5,
    MachineCultureSpiceMod=1.2,
    MachineCultureTechValueMod=1.2,
    WarChestSolariMod=1.5,
    ArtilleryRevealMod=1.66,
    ArtilleryAcquireMod=1.2,
    ArtilleryValueMod=1.1,
    MemocordersInfluenceMod=1.5,
    MemocordersValue3Mod=1.25,
    MemocordersValue2Mod=1.1,
    MemocordersValueConditionalMod=1.33,
    SonicSnoopersIntrigueMod=1.2,
    SonicSnoopersBadValueMod=1.25,
    SonicSnoopersGoodValueMod=1.1,
    TroopTransportsValueMod=1.5,
    HoloprojectorsAcquireMod=1.2,
    HoloprojectorsValueMod=1.2,
    TrainingDronesTroopMod=0.9,
    DetonationDevicesDreadnoughtMod=1.5,
    DetonationDevicesValueMod=1.25,
    DetonationDevicesValueNoDreadnoughtMod=-2.0,
    SpySatellitesSpiceMod=1.1,
    SpySatellitesValueLateMod=1.5,
    SpySatellitesValueMidMod=1.25,
    SpySatellitesValueEarlyMod=1.1,
    SpySatellitesValueFinalRoundMod=1.25,
    RestrictedOrdnanceHighCouncilMod=1.5,
    RestrictedOrdnanceValueMod=1.33,
    InvasionShipsAcquireMod=1.2,
    InvasionShipsValueMod=1.2,
    ShuttleFleetSolariMod=0.66,
    HoltzmanEngineAcquirePersuasion0Mod=0.75,
    HoltzmanEngineAcquirePersuasion2Mod=1.25,
    HoltzmanEngineAcquireTSMFMod=1.33,
    HoltzmanEngineValueTSMFMod=1.5,
    FlagshipSolariMod=1.5,
    FlagshipTroopMod=0.75,
    FlagshipValueMod=1.25,
    OverpoweringDreadResourceMod=2.0,
    OverpoweringDreadDeployMod=2.0,
    SpyValueEarly=1.66,
    SpyValueMid=1.66,
    SpyValueLate=1.33,
    ContractValueEarly=2.0,
    ContractValueMid=1.75,
    ContractValueLate=1.5,
    SandwormValueEarly=3.0,
    SandwormValueMid=3.0,
    SandwormValueLate=3.0,
    MakerHooksValueEarly=5.0,
    MakerHooksValueMid=4.0,
    MakerHooksValueLate=3.0,
    RecallAgentValueEarly=5.0,
    RecallAgentValueMid=5.0,
    RecallAgentValueLate=5.0,
    BlowWallValueEarly=0.0,
    BlowWallValueMid=0.0,
    BlowWallValueLate=0.0,
    BattleIconValueEarly=2.5,
    BattleIconValueMid=2.5,
    BattleIconValueLate=4.5,
    SpyRecallMod=4.5,
    ContractMod=0.33,
    WallModWaterMod=0.66,
    WallModSpaceMod=1.0,
    WallModHooksMod=1.5,
    ChaniCleverTacticianDeployMod=1.33,
    CovertOperationMod=2.5,
    DoubleAgentMod=0.5,
    LongLiveTheFightersMod=2.0,
    ReliableInformantMod=0.66,
    ArrakisInformantMod=0.66,
    WeirdingWomanMod=0.5,
    SpaceContractRewardValueModRatio=0.5,
    SpaceContractAgentIconsModRatio=0.17,
    SpaceContractResourceModRatio=0.16,
    SpaceContractSpyModRatio=0.16,
    SpaceContractOtherModRatio=0.17,
    HarvestContractRewardValueModRatio=0.5,
    HarvestContractResourceModRatio=0.33,
    HarvestContractBonusSpiceModRatio=0.33,
    AcquireContractRewardValueModRatio=0.34,
    AcquireContractHighCouncilModRatio=0.33,
    AcquireContractRoundModRatio=0.33,
    PostValueMatchingAgentIcon=1.0,
    PostValueFactionSpace=2.0,
    PostValueFactionSpaceHighValue=1.0,
    PostValueFactionSpaceGuildSpy=2.0,
    PostValueSwordmaster=2.0,
    PostValueInterstellarShipping=3.0,
    PostValueHaggaBasin=1.5,
    PostValueSietchTabr=1.5,
    PostValueUnseenNetwork=1.0,
    MuadDibFremenMod=1.25,
    MuadDibMakerHooksMod=1.33,
    LadyMargoFenringBeneGesseritSpiceMod=0.75,
    LadyAmberMetulliInfluenceMod=0.75,
    LadyJessicaSpiceAgonyMod=0.5,
    LadyJessicaOtherMemoriesMod=1.5,
    PrincessIrulanEmperorMod=1.0,
    StabanTuekUnseenNetworkMod=1.0,
    StabanTuekIconMod=1.2,
    StabanTuekPostMod=2.5,
    ShaddamCorrinoIVSignetHigh=-2.0,
    ShaddamCorrinoIVSignetMid=-1.0,
    SynergyTSMFUprisingMod=5.0,
    SynergySpyMod=0.5,
    SynergySpyCardMod=0.25,
    SynergyContractCompleted=0.75,
    SynergyContractCompletedMax=3.0,
    SynergyContractOpen=0.5,
    SynergyContractOpenMax=1.5,
    SynergyHaveHooksMod=1.5,
    SynergyHooksFremenInfluenceMod=1.0,
    ConflictInterestWormPotential=3.0,
    ExpectedStrengthWormPotentialA=2,
    ExpectedStrengthWormPotentialB=5,
    PotentialStrengthWormPotential=2,
    MatchModWildcard=1.5,
    MatchModStandard=2.0,
    BuyAccessSolariMod=1.2,
    CallToArmsAcquireMod=0.5,
    CouncilorsAmbitionMod=3.0,
    DepartForArrakisSGMod=0.25,
    DetonationHooksMod=1.3,
    DetonationBlowWallMod=0.33,
    DetonationSandWormMod=4.0,
    DevourHooksMod=1.1,
    DevourSandWormMod=1.1,
    ImperiumPoliticsInfluenceThreshold=3.0,
    InspireAweHooksMod=1.1,
    InspireAweSandWormMod=1.1,
    MarketOpportunitySpiceMod=1.1,
    MarketOpportunitySolariMod=1.2,
    MercenariesSolariMod=1.1,
    ShaddamsFavorEmperorMod=0.25,
    ShadowAllianceMod=1.2,
    SpecialMissionHooksMod=1.2,
    SpecialMissionSandWormMod=4.0,
    StrategicStockpilingSpiceMod=1.2,
    StrategicStockpilingWaterMod=1.2,
    StrategicStockpilingInfluenceMod=0.25,
    UnexpectedAlliesWaterMod=1.2,
    UnexpectedAlliesHooksMod=1.1,
    WeirdingCombatInfluenceMod=0.25,
    SpaceSpyUseInfiltrate3SpiesMod=0.5,
    SpaceSpyUseIntelligenceMod=1.25,
    MakerHooksFremenMod=1.2,
    WantSpyImperiumMod=1.15,
    SpringTheTrapSpyMod=1.5,
    SpyInfiltrateBoardSpaceValueMod=0.33,
    HooksModHalfOfOpponents=0.5,
    HooksModAllOpponents=0.5,
    WaterHooksMod=1.25,
)


EASY: Final = AIConstants(
    VictoryPointValueEarly=6.0,
    VictoryPointValueMid=6.0,
    VictoryPointValueLate=9.0,
    PersuasionValueEarly=1.0,
    PersuasionValueMid=0.75,
    PersuasionValueLate=0.66,
    StrengthValueEarly=0.66,
    StrengthValueMid=0.5,
    StrengthValueLate=0.5,
    SolariValueEarly=0.65,
    SolariValueMid=0.5,
    SolariValueLate=0.25,
    SolariMissingHighCouncilMod=0.85,
    SolariMissingSwordmasterMod=0.85,
    SpiceValueEarly=2.0,
    SpiceValueMid=1.5,
    SpiceValueLate=1.5,
    BonusSpiceMod=1.25,
    WaterValueEarly=2.25,
    WaterValueMid=1.8,
    WaterValueLate=1.3,
    TroopValueEarly=1.25,
    TroopValueMid=1.25,
    TroopValueLate=1.25,
    IntrigueValueEarly=2.25,
    IntrigueValueMid=2.5,
    IntrigueValueLate=2.75,
    IntrigueStealBonus=1.0,
    CardDrawValue=1.5,
    TrashCardEarly=2.75,
    TrashCardMid=2.0,
    TrashCardLate=1.0,
    DeployEarly=0.75,
    DeployMid=0.75,
    DeployLate=1.25,
    SolariShortValue=0.7,
    SpiceShortAmount=3.0,
    TroopShortAmount=2.0,
    WaterShortAmount=3.0,
    AcquireNewIconsBonus=-0.15,
    ConsolidationValueMod=0.15,
    SynergyModMaxValue=2.0,
    SynergyTSMFCardValue=2.0,
    SynergyTSMFHighPersuasionValue=0.5,
    SynergyFremenWithBondInDeck=0.5,
    SynergyBondWithFremenInDeck=0.66,
    SynergyBeneGesseritWithBondInDeck=0.75,
    SynergyWithFactionInDeck=0.5,
    GainSwordmasterEarly=50.0,
    GainSwordmasterMid=50.0,
    GainSwordmasterLate=10.0,
    GainHighCouncilEarly=15.0,
    GainHighCouncilMid=9.0,
    GainHighCouncilLate=5.0,
    GainFoldspaceEarly=3.0,
    GainFoldspaceMid=1.5,
    GainFoldspaceLate=0.5,
    GainMentatEarly=2.25,
    GainMentatMid=3.5,
    GainMentatLate=4.5,
    SellMelangeLowSolariValueThreshold=0.5,
    SellMelangeMidSolariValueThreshold=0.75,
    SellMelangeHighSolariValueThreshold=1.0,
    SellMelangeSpaceBonus=2.0,
    ConspireSpaceBonus=2.0,
    HeighlinerSpaceBonus=4.0,
    HeighlinerSpaceLowSupplyPenalty=-6.0,
    HeighlinerSpaceEarlyInRoundPenalty=-3.0,
    ControlSolariEarly=4.0,
    ControlSolariMid=1.75,
    ControlSolariLate=0.33,
    ControlSpiceEarly=6.0,
    ControlSpiceMid=3.0,
    ControlSpiceLate=1.0,
    InfluenceValue=2.25,
    GainInfluenceDefendAllianceMod=0.85,
    GainInfluenceDefendAllianceThreatenedMod=0.85,
    GainInfluenceVictoryPointMod=0.85,
    GainInfluenceVictoryPointLateMod=1.65,
    GainInfluenceAllianceMod=0.85,
    GainInfluenceAllianceLateMod=1.65,
    GainInfluenceThreatenedAllianceMod=0.85,
    GainInfluenceStealAllianceMod=0.85,
    GainInfluenceStealAllianceEndgameMod=3.0,
    GainInfluenceThreatenAllianceMod=0.85,
    GainInfluenceSecureAllianceMod=1.15,
    GainInfluenceAllianceImpossibleMod=1.15,
    GainInfluenceAllianceUnlikelyMod=1.15,
    GainInfluenceCardAllianceBonusMod=0.85,
    LoseInfluenceForfeitAllianceMod=0.85,
    LoseInfluenceForfeitAllianceCushionMod=0.85,
    LoseInfluenceForfeitVictoryPoint=0.85,
    LoseInfluenceAllianceImpossibleMod=1.15,
    LoseInfluenceAllianceUnlikelyMod=1.15,
    GainInfluenceSeizeOpeningMod=0.85,
    PoorMod=0.85,
    RichMod=1.15,
    FloodedMod=1.15,
    MinimumAcquireValueEarly=0.5,
    MinimumAcquireValueMid=0.5,
    MinimumAcquireValueLate=0.5,
    SolariNormalThreshold=3.0,
    SolariRichThreshold=8.0,
    SolariFloodedThreshold=9.0,
    SpiceNormalThreshold=3.0,
    SpiceRichThreshold=5.0,
    SpiceFloodedThreshold=8.0,
    WaterNormalThreshold=2.0,
    WaterRichThreshold=3.0,
    WaterFloodedThreshold=4.0,
    TroopNormalThreshold=2.0,
    TroopRichThreshold=4.0,
    TroopFloodedThreshold=5.0,
    ConflictAverageValue=14.0,
    ConflictInterestGarrisonUnitValue=2.5,
    ConflictInterestOpponentsWithAgentsPenalty=-1.5,
    ConflictInterestHandSwordValue=1.0,
    ConflictInterestIntrigueSwordValue=0.5,
    ConflictInterestHeighlinerPotential=5.0,
    ConflictPostureNoCompetitorsLowerBound=-10.0,
    ConflictPostureNoCompetitorsUpperBound=5.0,
    ConflictPostureSomeCompetitorsLowerBound=-2.5,
    ConflictPostureSomeCompetitorsUpperBound=12.5,
    ConflictPostureManyCompetitorsLowerBound=5.0,
    ConflictPostureManyCompetitorsUpperBound=20.0,
    ConflictPostureManyCompetitorsLowerBoundClimax=10.0,
    ConflictPostureManyCompetitorsUpperBoundClimax=15.0,
    ConflictPostureMidMod=0.85,
    ConflictPostureHighMod=0.85,
    CardPlayValueRevealPenalty=-0.5,
    OpulenceRevealBonus=5.0,
    OtherMemoryPlayBonusMod=0.66,
    SardaukarLegionRevealBonus=3.0,
    KwisatzHaderachDelayPenalty=-50.0,
    LietKynesFremenRevealBonus=3.0,
    TestOfHumanityRelevantOpponentMod=2.0,
    TheVoiceBlockHeighlinerBonus=2.0,
    GuildAmbassadorRevealBonus=4.0,
    GunThopterTroopRevealBonus=1.0,
    GurneyHalleckRevealBonus=1.5,
    WormRidersInfluenceRevealBonus=4.0,
    WormRidersAllianceRevealBonus=4.0,
    DukeLetoAtreidesSpiceValueMod=1.1,
    DukeLetoAtreidesPrudentDiplomacyInfluenceValueThreshold=2.4,
    BaronVladimirHarkonnenGetTroopsBonus=0.75,
    GlossuRabbanInfluenceValueBonus=0.75,
    GlossuRabbanTroopsValueMod=0.9,
    EarlMemnonThorvaldHighCouncilValueBonus=1.5,
    EarlMemnonThorvaldSpiceValueMod=0.9,
    CountessArianaThorvaldWaterValueMod=0.95,
    BriberyInfluenceThreshold=3.75,
    CalculatedHireMentatValueMod=0.33,
    CharismaBuyGainsThreshold=2.5,
    ChoamSharesSolariMod=1.25,
    CouncilorsDispensationSpiceThreshold=5.0,
    DemandRespectConflictMod=1.2,
    GainInfluenceValueThreshold=3.0,
    PlansWithinPlansEarlyInfluenceMod=1.25,
    PlansWithinPlansMeetRequisiteInfluenceMod=1.5,
    PrivateArmySpiceMod=1.1,
    RapidMobilizationDeployMod=0.5,
    RapidMobilizationTroopMod=1.3,
    RecruitmentMissionBuyGainsThreshold=1.33,
    ReinforcementsConflictInterestBonus=3.0,
    StagedIncidentDeployedTroopThreshold=4.0,
    StagedIncidentTotalTroopThreshold=3.0,
    StagedIncidentDeployMod=1.2,
    StagedIncidentTroopMod=1.2,
    TheSleeperMustAwakenSpiceMod=1.25,
    UrgentMissionMentatValueMod=0.5,
    WaterPeddlersUnionWaterThreshold=1.0,
    WindfallSolariThreshold=3.0,
    WindfallSwordmasterThreshold=8.0,
    WindfallChoamSharesThreshold=5.0,
    SpiceRefineryLowSolariValueThreshold=0.25,
    ExpectedStrengthHeighlinerPotential=7,
    PotentialStrengthHeighlinerPotential=10,
    SeekAlliesValueMod=0.33,
    IntrigueNormalThreshold=1.0,
    IntrigueRichThreshold=2.0,
    IntrigueFloodedThreshold=3.0,
    ResearchValueEarly=2.25,
    ResearchValueMid=2.25,
    ResearchValueLate=2.25,
    ResearchStepValueSingleHelixMod=0.75,
    ResearchStepValueDoubleHelixMod=1.0,
    ResearchTrackSpace17NoBadIntrigueMod=1.0,
    ResearchTrackSpace21ThirdSpaceMod=0.33,
    SpecimenValueEarly=1.0,
    SpecimenValueMid=1.0,
    SpecimenValueLate=0.75,
    SpecimenNormalThreshold=2.0,
    SpecimenRichThreshold=3.0,
    SpecimenFloodedThreshold=4.0,
    SpecimenGoodTleilaxuThreshold=1.5,
    SpecimenGoodTleilaxuBonus=1.0,
    TleilaxuValueEarly=2.25,
    TleilaxuValueMid=2.25,
    TleilaxuValueLate=2.25,
    TleilaxuTrackIntrigue=1.0,
    TleilaxuTrackVP=4.0,
    TleilaxuTrackLateGameMod=0.25,
    TrashIntrigueValue=-1.25,
    TwistedMentatBonus=5.0,
    TleilaxuGoodCardThreshold=3.0,
    AcquireTleilaxuReserveThreshold=1.0,
    AcquireTleilaxuReservePenalty=-5.0,
    GraftFewRemainingSpaceTargetsPenalty=-4.0,
    GraftBothCardsHaveGraftPenalty=-1.5,
    GraftAgentIconsPenalty=-3.0,
    TleilaxuShadowSynergyMod=0.5,
    TleilaxuHelixSynergyBonus=1.5,
    TleilaxuDoubleHelixSynergyBonus=2.0,
    TleilaxuGraftSynergyBonus=0.75,
    TleilaxuHighCostCardsSynergyMod=0.5,
    TleilaxuSwordmasterSynergyBonus=1.0,
    TleilaxuSligFarmerCardCountOffset=2.0,
    TleilaxuSligFarmerCardCountMod=0.5,
    TleilaxuReclaimForcesLateGameBonus=0.5,
    TleilaxuReclaimForcesNotLateGameMod=-0.5,
    TleilaxuReclaimForcesVPBonus=2.0,
    ChairdogGraftRevealMod=0.66,
    DissectingKitCardCostMod=-0.5,
    TleilaxuPuppetHighCouncilMod=1.2,
    EconomicPositioningSolariMod=1.5,
    EconomicPositioningDeploySolariThreshold=0.75,
    EconomicPositioningDeployMod=1.2,
    ReplacementEyesTrashValueMod=1.5,
    ShadoutMapesRevealValue=1.0,
    HighPriorityTravelAgentMod=0.5,
    ReplacementEyesAgentMod=3.5,
    SynergyWantsGraftMod=1.1,
    SynergyGraftMod=1.1,
    SynergyHelixMod=1.2,
    SynergyDoubleHelixMod=1.2,
    ImperiumCeremonyMod=1.33,
    StillsuitManufacturerMod=1.0,
    PoliticsPayoffMod=1.33,
    DiscardEnablerMod=1.1,
    DiscardIncentiveMod=1.1,
    DiscardEarly=-1.0,
    DiscardMid=-1.0,
    DiscardLate=-1.0,
    DreadnoughtEarly=6.0,
    DreadnoughtMid=5.0,
    DreadnoughtLate=3.0,
    NegotiateTechEarlyMod=0.9,
    NegotiateTechMidMod=0.8,
    NegotiateTechLateMod=0.7,
    FreighterEarly=4.2,
    FreighterMid=4.2,
    FreighterLate=4.2,
    BuyTechEarly=1.0,
    BuyTechMid=0.5,
    BuyTechLate=0.0,
    ConflictInterestGarrisonDreadnoughtValue=1.5,
    WeirdingWayValue=1.5,
    ImmediacyModValue=1.5,
    CourtIntrigueValue=2.0,
    InTheShadowsTrashValueMod=1.2,
    InTheShadowsTrashValueModBG=2.0,
    FreighterFleetTrashValueMod=2.1,
    IxGuildCompactTrashValueMod=1.1,
    TreacheryTrashValueMod=1.5,
    ConvincingArgumentTrashValueMod=-0.25,
    NegotiatedWithdrawalRetreatValue=2.5,
    NegotiatedWithdrawalDeployValueMod=1.5,
    DesertAmbushValue=3.0,
    DesertAmbushNoOppositionPenalty=-2.0,
    ImperialBasharSwordValue=0.33,
    IxianEngineerValue=2.0,
    CoordinationValue=1.0,
    ConscriptBeforeLateValue=1.75,
    HeavyLasgunCannonsValue=1.33,
    TessiaVerniusInfluenceMod=1.2,
    SpacingGuildRiseOfIxBonus=1.5,
    QuidProQuoSpiceMod=1.1,
    SecretForcesMod=2.2,
    DiversionTroopMod=2.2,
    AdvancedWeaponrySolariMod=1.2,
    GrandConspiracyDreadnoughtMod=1.33,
    GrandConspiracyHighCouncilMod=1.33,
    GrandConspiracyTSMFMod=1.33,
    GrandConspiracyInfluenceMod=1.5,
    MachineCultureSpiceMod=1.2,
    MachineCultureTechValueMod=1.2,
    WarChestSolariMod=1.5,
    ArtilleryRevealMod=1.66,
    ArtilleryAcquireMod=1.2,
    ArtilleryValueMod=1.1,
    MemocordersInfluenceMod=1.5,
    MemocordersValue3Mod=1.25,
    MemocordersValue2Mod=1.1,
    MemocordersValueConditionalMod=1.33,
    SonicSnoopersIntrigueMod=1.2,
    SonicSnoopersBadValueMod=1.25,
    SonicSnoopersGoodValueMod=1.1,
    TroopTransportsValueMod=1.5,
    HoloprojectorsAcquireMod=1.2,
    HoloprojectorsValueMod=1.2,
    TrainingDronesTroopMod=0.9,
    DetonationDevicesDreadnoughtMod=1.5,
    DetonationDevicesValueMod=1.25,
    DetonationDevicesValueNoDreadnoughtMod=-2.0,
    SpySatellitesSpiceMod=1.1,
    SpySatellitesValueLateMod=1.5,
    SpySatellitesValueMidMod=1.25,
    SpySatellitesValueEarlyMod=1.1,
    SpySatellitesValueFinalRoundMod=1.25,
    RestrictedOrdnanceHighCouncilMod=1.5,
    RestrictedOrdnanceValueMod=1.33,
    InvasionShipsAcquireMod=1.2,
    InvasionShipsValueMod=1.2,
    ShuttleFleetSolariMod=0.66,
    HoltzmanEngineAcquirePersuasion0Mod=0.75,
    HoltzmanEngineAcquirePersuasion2Mod=1.25,
    HoltzmanEngineAcquireTSMFMod=1.33,
    HoltzmanEngineValueTSMFMod=1.5,
    FlagshipSolariMod=1.5,
    FlagshipTroopMod=0.75,
    FlagshipValueMod=1.25,
    OverpoweringDreadResourceMod=2.0,
    OverpoweringDreadDeployMod=2.0,
    SpyValueEarly=1.66,
    SpyValueMid=1.66,
    SpyValueLate=1.33,
    ContractValueEarly=2.0,
    ContractValueMid=1.75,
    ContractValueLate=1.5,
    SandwormValueEarly=3.0,
    SandwormValueMid=3.0,
    SandwormValueLate=3.0,
    MakerHooksValueEarly=5.0,
    MakerHooksValueMid=4.0,
    MakerHooksValueLate=3.0,
    RecallAgentValueEarly=5.0,
    RecallAgentValueMid=5.0,
    RecallAgentValueLate=5.0,
    BlowWallValueEarly=0.0,
    BlowWallValueMid=0.0,
    BlowWallValueLate=0.0,
    BattleIconValueEarly=2.5,
    BattleIconValueMid=2.5,
    BattleIconValueLate=4.5,
    SpyRecallMod=4.5,
    ContractMod=0.33,
    WallModWaterMod=0.66,
    WallModSpaceMod=1.0,
    WallModHooksMod=1.5,
    ChaniCleverTacticianDeployMod=1.33,
    CovertOperationMod=2.5,
    DoubleAgentMod=0.5,
    LongLiveTheFightersMod=2.0,
    ReliableInformantMod=0.66,
    ArrakisInformantMod=0.66,
    WeirdingWomanMod=0.5,
    SpaceContractRewardValueModRatio=0.5,
    SpaceContractAgentIconsModRatio=0.17,
    SpaceContractResourceModRatio=0.16,
    SpaceContractSpyModRatio=0.16,
    SpaceContractOtherModRatio=0.17,
    HarvestContractRewardValueModRatio=0.5,
    HarvestContractResourceModRatio=0.33,
    HarvestContractBonusSpiceModRatio=0.33,
    AcquireContractRewardValueModRatio=0.34,
    AcquireContractHighCouncilModRatio=0.33,
    AcquireContractRoundModRatio=0.33,
    PostValueMatchingAgentIcon=1.0,
    PostValueFactionSpace=2.0,
    PostValueFactionSpaceHighValue=1.0,
    PostValueFactionSpaceGuildSpy=2.0,
    PostValueSwordmaster=2.0,
    PostValueInterstellarShipping=3.0,
    PostValueHaggaBasin=1.5,
    PostValueSietchTabr=1.5,
    PostValueUnseenNetwork=1.0,
    MuadDibFremenMod=1.25,
    MuadDibMakerHooksMod=1.33,
    LadyMargoFenringBeneGesseritSpiceMod=0.75,
    LadyAmberMetulliInfluenceMod=0.75,
    LadyJessicaSpiceAgonyMod=0.5,
    LadyJessicaOtherMemoriesMod=1.5,
    PrincessIrulanEmperorMod=1.0,
    StabanTuekUnseenNetworkMod=1.0,
    StabanTuekIconMod=1.2,
    StabanTuekPostMod=2.5,
    ShaddamCorrinoIVSignetHigh=-2.0,
    ShaddamCorrinoIVSignetMid=-1.0,
    SynergyTSMFUprisingMod=5.0,
    SynergySpyMod=0.5,
    SynergySpyCardMod=0.25,
    SynergyContractCompleted=0.75,
    SynergyContractCompletedMax=3.0,
    SynergyContractOpen=0.5,
    SynergyContractOpenMax=1.5,
    SynergyHaveHooksMod=1.5,
    SynergyHooksFremenInfluenceMod=1.0,
    ConflictInterestWormPotential=3.0,
    ExpectedStrengthWormPotentialA=2,
    ExpectedStrengthWormPotentialB=5,
    PotentialStrengthWormPotential=2,
    MatchModWildcard=1.5,
    MatchModStandard=2.0,
    BuyAccessSolariMod=1.2,
    CallToArmsAcquireMod=0.5,
    CouncilorsAmbitionMod=3.0,
    DepartForArrakisSGMod=0.25,
    DetonationHooksMod=1.3,
    DetonationBlowWallMod=0.33,
    DetonationSandWormMod=4.0,
    DevourHooksMod=1.1,
    DevourSandWormMod=1.1,
    ImperiumPoliticsInfluenceThreshold=3.0,
    InspireAweHooksMod=1.1,
    InspireAweSandWormMod=1.1,
    MarketOpportunitySpiceMod=1.1,
    MarketOpportunitySolariMod=1.2,
    MercenariesSolariMod=1.1,
    ShaddamsFavorEmperorMod=0.25,
    ShadowAllianceMod=1.2,
    SpecialMissionHooksMod=1.2,
    SpecialMissionSandWormMod=4.0,
    StrategicStockpilingSpiceMod=1.2,
    StrategicStockpilingWaterMod=1.2,
    StrategicStockpilingInfluenceMod=0.25,
    UnexpectedAlliesWaterMod=1.2,
    UnexpectedAlliesHooksMod=1.1,
    WeirdingCombatInfluenceMod=0.25,
    SpaceSpyUseInfiltrate3SpiesMod=0.5,
    SpaceSpyUseIntelligenceMod=1.25,
    MakerHooksFremenMod=1.2,
    WantSpyImperiumMod=1.15,
    SpringTheTrapSpyMod=1.5,
    SpyInfiltrateBoardSpaceValueMod=0.33,
    HooksModHalfOfOpponents=0.5,
    HooksModAllOpponents=0.5,
    WaterHooksMod=1.25,
)

# AILevel -> table, as ``worm.canis.ai.AIConstants..cctor`` registers them
# (level 3 is registered as Hard but nothing in the app sets it).
TABLES: Final = MappingProxyType({0: EASY, 1: MEDIUM, 2: HARD, 3: HARD})

# The getters AIMediumConstantsRef and AIEasyConstantsRef override.
OVERRIDDEN: Final = (
    "SolariMissingHighCouncilMod",
    "SolariMissingSwordmasterMod",
    "AcquireNewIconsBonus",
    "ConsolidationValueMod",
    "GainInfluenceDefendAllianceMod",
    "GainInfluenceDefendAllianceThreatenedMod",
    "GainInfluenceVictoryPointMod",
    "GainInfluenceAllianceMod",
    "GainInfluenceThreatenedAllianceMod",
    "GainInfluenceStealAllianceMod",
    "GainInfluenceThreatenAllianceMod",
    "GainInfluenceSecureAllianceMod",
    "GainInfluenceAllianceImpossibleMod",
    "GainInfluenceAllianceUnlikelyMod",
    "GainInfluenceCardAllianceBonusMod",
    "LoseInfluenceForfeitAllianceMod",
    "LoseInfluenceForfeitAllianceCushionMod",
    "LoseInfluenceForfeitVictoryPoint",
    "LoseInfluenceAllianceImpossibleMod",
    "LoseInfluenceAllianceUnlikelyMod",
    "GainInfluenceSeizeOpeningMod",
    "PoorMod",
    "RichMod",
    "FloodedMod",
    "MinimumAcquireValueEarly",
    "MinimumAcquireValueMid",
    "MinimumAcquireValueLate",
    "ConflictPostureMidMod",
    "ConflictPostureHighMod",
)
