"""Korean printed names of the cards the Korean edition was read for.

The Korean UI names a card by its Korean print where one is known here and
keeps the English name otherwise (``server.catalog`` hands both out, the
page picks by its language). Source: the Korea Boardgames editions of
Uprising, Bloodlines and Immortality, card faces read from photographs of
the retail cards in three Naver blog reviews (vampmiyu 223464306472,
223970873634, 223033440849); every title was read twice, independently, and
both readings agreed character for character (2026-09-22/23). The photos
and the per-crop matching tables (``matching.csv``) are kept outside git, in
the assets checkout's ``reference/naver-vampmiyu-<post>/`` on the machine
that made them (the WSL laptop; the assets README says why).

Keyed like the display catalog's sections (``cards`` holds Imperium,
Tleilaxu, starting, Reserve and promo cards; ``skills`` the Sardaukar
Commander Skills, ``tech`` the Tech tiles). Navigation cards print no title
and board spaces keep their English names, so neither is here. The
engine's English name sometimes carries a distinguisher the card does not
print: a contract's numeral ("Arrakeen I") or spice threshold ("Harvest
3+"), and a Skirmish's battle icon. The Korean name carries the same
distinguisher, the battle icons in the glossary's words (크리스나이프 /
사막쥐 / 오니솝터 `[Main p. 20]`, 와일드 `[Bloodlines p. 5]`,
``docs/rules/glossary-ko.md``).
"""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

_CARDS: Final[dict[str, str]] = {
    "arrakis_observer": "아라키스 관찰자",
    "arrakis_revolt": "아라키스 반란",
    "beguiling_pheromones": "유혹적인 페로몬",
    "bene_gesserit_operative": "베네 게세리트 첩보원",
    "bene_tleilax_lab": "베네 틀레이락스 연구소",
    "bene_tleilax_researcher": "베네 틀레이락스 연구자",
    "blank_slate": "새하얀 도화지",
    "bombast": "호언장담",
    "branching_path": "갈림길",
    "calculus_of_power": "힘의 계산법",
    "captured_mentat": "붙잡힌 멘타트",
    "cargo_runner": "화물 운반사",
    "chairdog": "의자개",
    "chani_clever_tactician": "영리한 전술가, 챠니",
    "choam_demands": "초암의 요구",
    "clandestine_meeting": "비밀 회의",
    "command_center": "지휘본부",
    "contaminator": "오염시키는 자",
    "convincing_argument": "합리적 주장",
    "corrino_genes": "코리노 유전자",
    "corrinth_city": "코린트 시티",
    "corrupt_bureaucrat": "부패한 관료",
    "corrupt_smuggler": "부패한 밀수업자",
    "covert_operation": "비밀 작전",
    "dagger": "단검",
    "dangerous_rhetoric": "위험한 미사여구",
    "delivery_agreement": "배송 협정",
    "delivery_logistics": "배송 물류 관리",
    "desert_power": "사막의 힘",
    "desert_survival": "사막 생존자",
    "diplomacy": "외교",
    "disruption_tactics": "방해 전술",
    "dissecting_kit": "해부도구 세트",
    "double_agent": "이중 스파이",
    "dune_the_desert_planet": "사막 행성 듄",
    "ecological_testing_station": "생태 시험소",
    "eliminate_allies": "협력자 제거",
    "elite_forces": "정예 부대",
    "engineered_miracle": "계획된 기적",
    "experimentation": "실험",
    "face_dancer": "얼굴의 춤꾼",
    "face_dancer_initiate": "얼굴의 춤꾼 견습생",
    "fedaykin_stilltent": "페다이킨 사막 텐트",
    "for_humanity": "인류를 위하여",
    "fremen_war_name": "프레멘 성인 이름",
    "from_the_tanks": "탱크에서 나온 자",
    "ghola": "골라",
    "guild_envoy": "길드 특사",
    "guild_impersonator": "길드원 사칭자",
    "guild_spy": "길드 스파이",
    "hidden_missive": "비밀 서신",
    "high_priority_travel": "최우선 순위 항행",
    "holy_war": "신성한 전쟁",
    "i_believe": "난 믿는다",
    "imperial_spymaster": "제국 스파이 대장",
    "imperial_throneship": "황제의 우주선",
    "imperium_ceremony": "임페리움 의식",
    "in_high_places": "높은 자리에서",
    "industrial_espionage": "산업 스파이",
    "intelligence_training": "첩보 교육",
    "interstellar_conspiracy": "성간 모의",
    "interstellar_trade": "성간 교역",
    "ixian_ambassador": "익스 대사",
    "junction_headquarters": "중계 본부",
    "keys_to_power": "권력의 열쇠",
    "leadership": "리더십",
    "lisan_al_gaib": "리산 알 가입",
    "litany_against_fear": "두려움에 맞서는 기도",
    "long_live_the_fighters": "전사들이여 영원하라",
    "long_reach": "광대한 세력 범위",
    "maker_keeper": "메이커 사육사",
    "maula_pistol": "마울라 권총",
    "mercantile_affairs": "상업 활동",
    "northern_watermaster": "북부 물감독관",
    "occupation": "점거",
    "organ_merchants": "장기 상인",
    "overthrow": "타도",
    "paracompass": "파라컴퍼스",
    "piter_genius_advisor": "천재적인 조언자, 파이터",
    "planned_coupling": "계획된 교배",
    "pointing_the_way": "길을 가리키다",
    "possible_futures": "가능한 미래",
    "prepare_the_way": "길을 준비하라",
    "price_is_no_object": "값은 문제가 아니다",
    "priority_contracts": "우선 계약",
    "public_spectacle": "대중의 구경거리",
    "quash_rebellion": "모반 진압",
    "rebel_supplier": "반란군 공급자",
    "reclaimed_forces": "되돌아온 병사들",
    "reconnaissance": "첩보 수집",
    "reliable_informant": "믿을 만한 정보원",
    "replacement_eyes": "인공 눈",
    "ruthless_leadership": "무자비한 리더십",
    "sandwalk": "사막의 걸음걸이",
    "sardaukar_coordination": "사다우카 편성",
    "sardaukar_quartermaster": "사다우카 보급관",
    "sardaukar_soldier": "사다우카 병사",
    "sardaukar_standard": "사다우카 깃발",
    "scientific_breakthrough": "과학 기술 혁신",
    "seek_allies": "동맹 물색",
    "shadout_mapes": "샤도우트 메입스",
    "shishakli": "시샤클리",
    "show_of_strength": "세력 과시",
    "shrouded_counsel": "베일에 싸인 조언",
    "signet_ring": "인장 반지",
    "slig_farmer": "슬리그 사육자",
    "smuggler_s_harvester": "밀수꾼의 채취기",
    "smuggler_s_haven": "밀수꾼의 피난처",
    "southern_elders": "남부 원로",
    "southern_faith": "남부 종교",
    "space_time_folding": "시공간 접기",
    "spacing_guild_s_favor": "우주 항행 길드의 호의",
    "spiritual_fervor": "정신적 열의",
    "spy_network": "스파이 네트워크",
    "steersman": "조타수",
    "stilgar_the_devoted": "충실한 자, 스틸가",
    "stillsuit_manufacturer": "스틸슈트 제조자",
    "stitched_horror": "공포의 누더기 괴물",
    "strike_fleet": "공습 함대",
    "subject_x_137": "실험체 X-137",
    "subversive_advisor": "불온한 조언자",
    "the_spice_must_flow": "스파이스는 흘러야 한다",
    "throne_room_politics": "알현실 정치",
    "tleilaxu_infiltrator": "틀레이락스 침입자",
    "tleilaxu_master": "틀레이락스의 주인",
    "tleilaxu_surgeon": "틀레이락스 수술의",
    "treacherous_maneuver": "기만적인 계책",
    "tread_in_darkness": "어둠 속 발소리",
    "truthtrance": "진실의 무아지경",
    "twisted_mentat": "뒤틀린 멘타트",
    "undercover_asset": "첩보 요원",
    "unnatural_reflexes": "비정상적인 반사 신경",
    "unswerving_loyalty": "변함없는 충성심",
    "urgent_shigawire": "다급한 시거와이어",
    "usurp": "찬탈",
    "weirding_woman": "기묘한 여성",
    "wheels_within_wheels": "얽히고설킨 상황",
}


_INTRIGUE: Final[dict[str, str]] = {
    "backed_by_choam": "초암 공사의 후원",
    "battlefield_research": "전장 분석",
    "breakthrough": "혁신",
    "choam_profits": "초암 공사 수익",
    "counterattack": "역습",
    "crysknife": "크리스나이프",
    "depart_for_arrakis": "아라키스를 향해",
    "desert_support": "사막 지원",
    "disguised_bureaucrat": "위장한 관료",
    "economic_positioning": "경제적 지위 확립",
    "emperor_s_invitation": "황제의 초대",
    "gruesome_sacrifice": "소름끼치는 희생",
    "harvest_cells": "세포 수확",
    "illicit_dealings": "불법 거래",
    "leverage": "레버리지",
    "rapid_engineering": "급속 공학",
    "reach_agreement": "합의 달성",
    "shadowy_bargain": "은밀한 협상",
    "sleeper_unit": "잠복 유닛",
    "study_melange": "멜란지 연구",
    "tenuous_bond": "빈약한 유대",
    "tleilaxu_puppet": "틀레이락스 꼭두각시",
    "twisted_discerning": "통찰",
    "vicious_talents": "포악한 재능",
    "withdrawal_agreement": "병력 철수 합의",
}


_CONTRACTS: Final[dict[str, str]] = {
    "acquire": "획득",
    "arrakeen_i": "아라킨 I",
    "arrakeen_ii": "아라킨 II",
    "bloodlines_deliver_supplies": "보급품 배송",
    "bloodlines_earn_any_alliance": "아무 팩션과 동맹이 됨",
    "bloodlines_harvest_3": "채취 3+",
    "bloodlines_harvest_4": "채취 4+",
    "bloodlines_high_council": "원로회",
    "bloodlines_immediate": "즉시",
    "bloodlines_secrets": "비밀",
    "bloodlines_spice_refinery": "스파이스 정제소",
    "deliver_supplies": "보급품 배송",
    "espionage_i": "첩보 활동 I",
    "espionage_ii": "첩보 활동 II",
    "harvest_3": "채취 3+",
    "harvest_3_contract": "채취 3+",
    "harvest_4": "채취 4+",
    "harvest_4_contract": "채취 4+",
    "heighliner_i": "하이라이너 I",
    "heighliner_ii": "하이라이너 II",
    "heighliner_iii": "하이라이너 III",
    "high_council_i": "원로회 I",
    "high_council_ii": "원로회 II",
    "immediate": "즉시",
    "research_station_i": "연구 기지 I",
    "research_station_ii": "연구 기지 II",
    "sardaukar_i": "사다우카 I",
    "sardaukar_ii": "사다우카 II",
}


_CONFLICTS: Final[dict[str, str]] = {
    "battle_for_arrakeen": "아라킨 대전투",
    "battle_for_imperial_basin": "제국 분지 점령전",
    "battle_for_spice_refinery": "스파이스 정제소 대전투",
    "choam_security": "초암 공사 방위",
    "propaganda": "프로파간다",
    "protect_the_sietches": "시치 방어전",
    "secure_imperial_basin": "제국 분지 확보",
    "seize_spice_refinery": "스파이스 정제소 장악",
    "shadow_contest": "그림자 속 암투",
    "siege_of_arrakeen": "아라킨 공성전",
    "skirmish_crysknife": "소규모 전투 (크리스나이프)",
    "skirmish_desert_mouse": "소규모 전투 (사막쥐)",
    "skirmish_ornithopter": "소규모 전투 (오니솝터)",
    "skirmish_wild": "소규모 전투 (와일드)",
    "spice_freighters": "스파이스 화물선",
    "storms_in_the_south": "남부에 부는 폭풍",
    "test_of_loyalty": "충성심 시험",
    "trade_dispute": "무역 분쟁",
}


_LEADERS: Final[dict[str, str]] = {
    "chani": "챠니",
    "count_hasimir_fenring": "하시미르 펜링 백작",
    "duncan_idaho": "던칸 아이다호",
    "esmar_tuek": "에스마르 튜엑",
    "feyd_rautha_harkonnen": "페이드 로타 하코넨",
    "gaius_helen_mohiam": "가이우스 헬렌 모히암",
    "gurney_halleck": "거니 할렉",
    "kota_odax_of_ix": "익스의 코타 오닥스",
    "lady_amber_metulli": "레이디 앰버 메툴리",
    "lady_jessica": "레이디 제시카",
    "lady_margot_fenring": "레이디 마고트 펜링",
    "liet_kynes": "리에트 카인즈",
    "muad_dib": "무앗딥",
    "piter_de_vries": "파이터 드 브리즈",
    "princess_irulan": "이룰란 공주",
    "shaddam_corrino_iv": "샤담 코리노 4세",
    "staban_tuek": "스타반 튜엑",
    "steersman_y_rkoon": "조타수 이르쿤",
}


_SKILLS: Final[dict[str, str]] = {
    "canny": "영리함",
    "charismatic": "카리스마적임",
    "desperate": "필사적임",
    "driven": "의욕적임",
    "fierce": "맹렬함",
    "hardy": "강인함",
    "loyal": "충성스러움",
}


_TECH: Final[dict[str, str]] = {
    "advanced_data_analysis": "고급 데이터 분석",
    "choam_transports": "초암 수송선",
    "delivery_bay": "운송 구획",
    "forbidden_weapons": "금지된 무기",
    "gene_locked_vault": "유전자 인식 금고",
    "glowglobes": "발광구",
    "navigation_chamber": "운항실",
    "ornithopter_fleet": "오니솝터 부대",
    "panopticon": "파놉티콘",
    "planetary_array": "행성 군사력",
    "plasteel_blades": "플라스틸 칼",
    "rapid_dropships": "고속 수송선",
    "sardaukar_high_command": "사다우카 총사령부",
    "self_destroying_messages": "자폭 메시지",
    "servo_receivers": "서보 수신기",
    "spy_drones": "스파이 드론",
    "suspensor_suits": "반중력 의복",
    "training_depot": "신병 훈련소",
}


KOREAN_CARD_NAMES: Final[Mapping[str, Mapping[str, str]]] = MappingProxyType(
    {
        "cards": MappingProxyType(_CARDS),
        "intrigue": MappingProxyType(_INTRIGUE),
        "contracts": MappingProxyType(_CONTRACTS),
        "conflicts": MappingProxyType(_CONFLICTS),
        "leaders": MappingProxyType(_LEADERS),
        "skills": MappingProxyType(_SKILLS),
        "tech": MappingProxyType(_TECH),
    }
)
"""``{catalog section: {id: Korean name}}``; an absent id keeps its English."""
