"""Static display catalog of public printed content for the web UI.

Everything here is printed, table-visible card data taken from the content
manifests — names, costs, icons, and English effect text generated by the
``dune_imperium.display`` package from the same data the engine executes —
so the UI can render informative cards without ever touching hidden state.
The catalog is immutable for a given ruleset build and set of local card
images and safe to cache on the client.

``image_index`` is the server's resolved card-image index — ``(catalog
kind, content_id, "<language>/<path>")`` triples from the private asset
manifest (``display.images``) for files that actually exist — so a
machine without the assets checkout serves the same catalog with every
``image`` field null. It is the English UI's (English picture first);
``image_index_ko`` is the Korean UI's, and wherever the two differ an entry
carries ``image_ko`` beside ``image``. Cards whose Korean print is known
(``display.names_ko``) carry ``name_ko`` beside ``name``; the page shows
the pair of its language. An entry's engine-*generated* effect text (as
opposed to printed card wording, which stays English) carries its Korean
twin the same way, suffixed ``_ko``: so far ``contracts[].condition_ko``/
``reward_ko``, ``conflicts[].rewards_ko`` (``display.structs``'s ``_ko``
renderers), ``cards[].text_ko`` (``display.cards``'s
``personal_card_text_ko``, Step K2) and ``intrigue[].text_ko``
(``display.effect_dsl_text_ko``'s ``intrigue_card_text_ko``, Step K3, one
line per printed option, aligned index-for-index with ``text``);
``spaces[].options[].effect_ko``/``.choam_options[].effect_ko``/
``.immortality.options[].effect_ko``, ``spaces[].notes_ko``,
``skills[].text_ko`` and ``tech[].text_ko`` (``display.spaces`` and
``display.bloodlines``'s ``_ko`` renderers, Step K4); more fields grow this
list as later work translates their generators. ``leaders[].ability_ko``/
``ability_text_ko``/``signet_ko``/``signet_text_ko``/``notes_ko`` (Step K5)
are the one exception to "printed card wording stays English": a Leader
face's own ability/Signet Ring name and text are hand-transcribed from the
Korean card print the same way the English is (``display.leaders_ko``'s
``LEADER_FACE_TEXTS_KO``), not composed from engine data, and are absent for
``reverend_mother_jessica``, whose flip face has no Korean scan.
``icon_files``, ``token_files`` and ``board_image`` work the same way for
the rulebook icon set (``/icons/...``), the pictured
Combat markers (``/tokens/...``, ``display.token_images``) and the local board
scan (``/board-image``): the catalog also carries the percent coordinates
that place the live state on that scan (``display.board_layout``).
"""

from functools import cache
from urllib.parse import quote

from dune_imperium.content.bloodlines.sardaukar import SKILLS
from dune_imperium.content.bloodlines.tech import TECH_TILES
from dune_imperium.content.immortality.board import (
    FIRST_GENETIC_MARKER_COLUMN,
    RESEARCH_SPACES,
    RESEARCH_START_ID,
    SECOND_GENETIC_MARKER_COLUMN,
    TLEILAXU_SETUP_SPICE_SPACE,
    TLEILAXU_TRACK,
)
from dune_imperium.content.immortality.tleilaxu import (
    RECLAIMED_FORCES,
    TLEILAXU_CARDS_BY_ID,
)
from dune_imperium.content.uprising.board import BOARD_SPACES_BY_ID, OBSERVATION_POSTS
from dune_imperium.content.uprising.conflicts import CONFLICTS, ConflictDefinition
from dune_imperium.content.uprising.contracts import CONTRACTS_BY_ID
from dune_imperium.content.uprising.imperium import IMPERIUM_CARDS_BY_ID
from dune_imperium.content.uprising.intrigue import INTRIGUE_CARDS_BY_ID
from dune_imperium.content.uprising.leaders import LEADERS
from dune_imperium.content.uprising.objectives import OBJECTIVES
from dune_imperium.content.uprising.reserve import RESERVE_STACKS
from dune_imperium.content.uprising.starting_cards import STARTING_CARDS_BY_ID
from dune_imperium.display import (
    LEADER_FACE_TEXTS,
    LEADER_FACE_TEXTS_KO,
    available_icons,
    available_strength_tokens,
    conflict_rewards_texts,
    conflict_rewards_texts_ko,
    contract_condition_text,
    contract_condition_text_ko,
    contract_reward_text,
    contract_reward_text_ko,
    intrigue_card_text,
    intrigue_card_text_ko,
    personal_card_text,
    personal_card_text_ko,
    space_is_implemented,
    space_notes,
    space_notes_ko,
    space_option_count,
    space_option_effects,
    space_option_effects_ko,
)
from dune_imperium.display.bene_tleilax_layout import bene_tleilax_layout
from dune_imperium.display.bloodlines import (
    skill_effect_text,
    skill_effect_text_ko,
    tech_ability_text,
    tech_ability_text_ko,
    tech_acquire_text,
    tech_acquire_text_ko,
)
from dune_imperium.display.board_layout import (
    COMMANDER_ANCHOR,
    COMMANDER_HEIGHT,
    COMMANDER_PICTURE_BASE,
    LEADER_TILE_BOXES,
    POST_POINTS,
    POST_SIZE,
    RESEARCH_STATION_OVERLAY_BOX,
    SHIELD_WALL_BOX,
    SHIELD_WALL_ROTATION,
    SPACE_BOXES,
    SPACE_FRAME_CUT,
    marker_layout,
)
from dune_imperium.display.images import (
    IXIAN_EMBASSY_IMAGE_ID,
    RESEARCH_STATION_OVERLAY_IMAGE_ID,
)
from dune_imperium.display.leader_layout import leader_layout
from dune_imperium.display.names_ko import KOREAN_CARD_NAMES
from dune_imperium.display.token_images import (
    MAKER_HOOKS_TOKEN_FILENAME,
    SARDAUKAR_COMMANDER_TOKEN_FILENAME,
    SHIELD_WALL_TOKEN_FILENAME,
    available_alliance_tokens,
)
from dune_imperium.server.sessions import JsonObject, JsonValue


@cache
def build_catalog(
    image_index: frozenset[tuple[str, str, str]] = frozenset(),
    icon_files: frozenset[str] = frozenset(),
    board_image: bool = False,
    *,
    bene_tleilax_image: bool = False,
    token_files: frozenset[str] = frozenset(),
    asset_versions: frozenset[tuple[str, str]] = frozenset(),
    image_index_ko: frozenset[tuple[str, str, str]] = frozenset(),
) -> JsonObject:
    """Return every display mapping the browser UI needs, keyed by ID.

    ``asset_versions`` pairs an asset URL with a token of the file behind it
    (``asset_url_versions`` in ``server.app``). The catalog hands such a URL
    out as ``<url>?v=<token>``: the owner replaces pictures in place, and a
    browser that cached the old file under the same URL would go on showing
    it without asking (a replaced Tuek's Sietch did, 2026-09-18).
    """

    versions = dict(asset_versions)

    def versioned(url: str) -> str:
        version = versions.get(url)
        return f"{url}?v={version}" if version else url

    # Card pictures as final URLs, so every ``_image_url`` below is versioned.
    image_files: dict[tuple[str, str], str] = {
        (kind, content_id): versioned(card_image_url(path))
        for kind, content_id, path in image_index
    }
    # The Korean UI's picture by the English one's URL, where they differ.
    # Two entries sharing an English picture must share the Korean one too,
    # or pairing by URL would give one of them the other's picture.
    korean_images: dict[str, str] = {}
    for kind, content_id, path in image_index_ko:
        english = image_files.get((kind, content_id))
        korean = versioned(card_image_url(path))
        if english is None or english == korean:
            continue
        if korean_images.setdefault(english, korean) != korean:
            raise ValueError(f"{english} pairs with two Korean pictures")
    cards: dict[str, JsonValue] = {}
    for card_id, starter in STARTING_CARDS_BY_ID.items():
        cards[card_id] = _personal_card(
            starter.card.name,
            cost=None,
            persuasion=starter.reveal_persuasion,
            swords=starter.reveal_strength,
            factions=tuple(faction.value for faction in starter.factions),
            agent_icons=tuple(icon.value for icon in starter.agent_icons),
            text=personal_card_text(starter),
            text_ko=personal_card_text_ko(starter),
            image=_image_url("other", card_id, image_files),
        )
    for stack in RESERVE_STACKS:
        cards[stack.card.card_id] = _personal_card(
            stack.card.name,
            cost=stack.acquisition_cost,
            persuasion=stack.reveal_persuasion,
            swords=stack.reveal_strength,
            factions=(),
            agent_icons=tuple(icon.value for icon in stack.agent_icons),
            text=personal_card_text(stack),
            text_ko=personal_card_text_ko(stack),
            image=_image_url("other", stack.card.card_id, image_files),
        )
    for card_id, entry in IMPERIUM_CARDS_BY_ID.items():
        cards[card_id] = _personal_card(
            entry.card.name,
            cost=entry.acquisition_cost,
            persuasion=entry.reveal_persuasion,
            swords=entry.reveal_strength,
            factions=tuple(faction.value for faction in entry.factions),
            agent_icons=tuple(icon.value for icon in entry.agent_icons),
            text=personal_card_text(entry),
            text_ko=personal_card_text_ko(entry),
            image=_image_url("imperium", card_id, image_files),
            # Immortality's Imperium deck has Graft cards too (Dissecting
            # Kit, Corrino Genes, ...), not only the Tleilaxu deck.
            graft=entry.graft,
        )
    # Immortality: the Tleilaxu deck (bought with specimens, not Persuasion)
    # and the fixed Reclaimed Forces card of the Tleilaxu Row.
    for card_id, tleilaxu_entry in (
        *TLEILAXU_CARDS_BY_ID.items(),
        (RECLAIMED_FORCES.card.card_id, RECLAIMED_FORCES),
    ):
        cards[card_id] = _personal_card(
            tleilaxu_entry.card.name,
            cost=None,
            persuasion=tleilaxu_entry.reveal_persuasion,
            swords=tleilaxu_entry.reveal_strength,
            factions=tuple(faction.value for faction in tleilaxu_entry.factions),
            agent_icons=tuple(icon.value for icon in tleilaxu_entry.agent_icons),
            text=personal_card_text(tleilaxu_entry),
            text_ko=personal_card_text_ko(tleilaxu_entry),
            image=_image_url("tleilaxu", card_id, image_files),
            specimens=tleilaxu_entry.specimen_cost,
            graft=tleilaxu_entry.graft,
        )

    intrigue: dict[str, JsonValue] = {}
    for intrigue_id, intrigue_entry in INTRIGUE_CARDS_BY_ID.items():
        timings: list[JsonValue] = [
            timing
            for timing in sorted(
                {option.timing.value for option in intrigue_entry.options}
            )
        ]
        intrigue[intrigue_id] = {
            "name": intrigue_entry.card.name,
            "timings": timings,
            "text": list(intrigue_card_text(intrigue_entry)),
            "text_ko": list(intrigue_card_text_ko(intrigue_entry)),
            "image": _image_url("intrigue", intrigue_id, image_files),
        }

    leader_layouts = leader_layout()
    leaders: dict[str, JsonValue] = {}
    for leader in LEADERS:
        leaders[leader.leader_id] = _leader_face(
            leader.name,
            ability=leader.ability_name,
            signet=leader.signet_name,
            face_id=leader.leader_id,
            image_files=image_files,
            layout=leader_layouts.get(leader.leader_id),
        )
        if leader.alternate_face_id is not None:
            leaders[leader.alternate_face_id] = _leader_face(
                leader.alternate_face_id.replace("_", " ").title(),
                ability=leader.alternate_ability_name,
                signet=leader.alternate_signet_name,
                face_id=leader.alternate_face_id,
                image_files=image_files,
            )

    skills: dict[str, JsonValue] = {
        skill.skill_id: {
            "name": skill.name,
            "kind": skill.kind.value,
            "text": [skill_effect_text(skill)],
            "text_ko": [skill_effect_text_ko(skill)],
            "image": _image_url("skill", skill.skill_id, image_files),
        }
        for skill in SKILLS
    }
    tech: dict[str, JsonValue] = {
        tile.tech_id: {
            "name": tile.name,
            "cost": tile.cost,
            "acquire": tech_acquire_text(tile),
            "ability": tech_ability_text(tile),
            "text": [
                *(
                    (f"Acquire: {tech_acquire_text(tile)}",)
                    if tech_acquire_text(tile)
                    else ()
                ),
                tech_ability_text(tile),
            ],
            # Korean twin of "text" (Step K4): "{acquire}: " matches the
            # bare box-label placeholder convention every other timing/box
            # label in this feature uses ({reveal_turn}:, {endgame}:, ...).
            "text_ko": [
                *(
                    (f"{{acquire}}: {tech_acquire_text_ko(tile)}",)
                    if tech_acquire_text_ko(tile)
                    else ()
                ),
                tech_ability_text_ko(tile),
            ],
            "flips": tile.flips,
            "choam_only": tile.choam_only,
            "image": _image_url("tech", tile.tech_id, image_files),
        }
        for tile in TECH_TILES
    }

    catalog: JsonObject = {
        "cards": cards,
        "intrigue": intrigue,
        # Immortality: the Bene Tleilax board's research hexes (column,
        # row, printed bonus) and Tleilaxu track, for the board panel.
        "bene_tleilax": {
            "research_spaces": [
                {
                    "id": space.space_id,
                    "column": space.column,
                    "row": space.row,
                    "bonus": space.bonus.value,
                }
                for space in RESEARCH_SPACES
            ],
            "research_start": RESEARCH_START_ID,
            "genetic_marker_columns": [
                FIRST_GENETIC_MARKER_COLUMN,
                SECOND_GENETIC_MARKER_COLUMN,
            ],
            "tleilaxu_track": [bonus.value for bonus in TLEILAXU_TRACK],
            "tleilaxu_spice_space": TLEILAXU_SETUP_SPICE_SPACE,
            # The owner's scan and the percent layout drawn over it; without
            # the scan the client draws a synthetic grid.
            "image": (
                versioned("/bene-tleilax-image") if bene_tleilax_image else None
            ),
            "layout": bene_tleilax_layout(),
        },
        # Bloodlines Skill tiles and Tech Module tiles, keyed by their ids.
        "skills": skills,
        "tech": tech,
        "embassy_image": _image_url("other", IXIAN_EMBASSY_IMAGE_ID, image_files),
        "contracts": {
            contract_id: {
                "name": definition.card.name,
                "condition": contract_condition_text(definition.condition),
                "condition_ko": contract_condition_text_ko(definition.condition),
                "reward": contract_reward_text(definition.reward),
                "reward_ko": contract_reward_text_ko(definition.reward),
                "immediate": definition.completes_immediately,
                "image": _image_url("contract", contract_id, image_files),
            }
            for contract_id, definition in CONTRACTS_BY_ID.items()
        },
        "conflicts": {
            conflict.card.card_id: {
                "name": conflict.card.name,
                "tier": conflict.tier.value,
                "icon": (
                    conflict.battle_icon.value
                    if conflict.battle_icon is not None
                    else None
                ),
                "shield_wall_protected": conflict.shield_wall_protected,
                "rewards": _conflict_rewards(conflict),
                "rewards_ko": _conflict_rewards_ko(conflict),
                "image": _image_url(
                    "conflict", conflict.card.card_id, image_files
                ),
            }
            for conflict in CONFLICTS
        },
        "leaders": leaders,
        "spaces": {
            space_id: _space(space_id, image_files)
            for space_id in BOARD_SPACES_BY_ID
        },
        "objectives": {
            objective.objective_id: {
                "name": objective.objective_id.replace("_", " ").title(),
                "icon": objective.battle_icon.value,
            }
            for objective in OBJECTIVES
        },
        # The frame every space's "box" follows: its two cut corners as
        # percents of the box's width and height.
        "space_frame": {"cut": list(SPACE_FRAME_CUT)},
        "posts": {
            post_id: [x, y] for post_id, (x, y) in POST_POINTS.items()
        },
        # The board spaces each post watches: a post has no printed name, so
        # the client names it after them ("관측소 (Hagga Basin)") wherever
        # the engine hands it a post id — log, action list, board title.
        "post_spaces": {
            post.post_id: list(post.connected_space_ids)
            for post in OBSERVATION_POSTS
        },
        # The printed post disc's diameter, percent of the scan's width.
        "post_size": POST_SIZE,
        "icons": {
            name: versioned(f"/icons/{filename}")
            for name, filename in available_icons(icon_files).items()
        },
        "board_image": versioned("/board-image") if board_image else None,
        # Each seat's pictured Combat marker (sword face and "+20" face), or
        # null where the local token directory lacks either face: the client
        # then draws its own seat token.
        "strength_tokens": [
            None
            if faces is None
            else {
                "front": versioned(f"/tokens/{faces[0]}"),
                "plus20": versioned(f"/tokens/{faces[1]}"),
            }
            for faces in available_strength_tokens(token_files)
        ],
        # The Shield Wall token on its marked position [Main p. 4]: the
        # picture (null without the local file) and where it lies.
        "shield_wall": {
            "image": (
                versioned(f"/tokens/{SHIELD_WALL_TOKEN_FILENAME}")
                if SHIELD_WALL_TOKEN_FILENAME in token_files
                else None
            ),
            "box": list(SHIELD_WALL_BOX),
            "rotation": SHIELD_WALL_ROTATION,
        },
        # The Maker Hooks token's picture (null without the local file; the
        # client then draws the rulebook icon in the garrison's slot) and the
        # Alliance tokens' pictures by Faction (absent ones are drawn).
        "maker_hooks_token": (
            versioned(f"/tokens/{MAKER_HOOKS_TOKEN_FILENAME}")
            if MAKER_HOOKS_TOKEN_FILENAME in token_files
            else None
        ),
        "alliance_tokens": {
            faction: versioned(f"/tokens/{filename}")
            for faction, filename in available_alliance_tokens(token_files).items()
        },
        # A Sardaukar Commander on a board space [Bloodlines p. 3]: the
        # rulebook figure's picture (null without the local file; the client
        # then draws a mark) and where it stands on the space's frame —
        # ``anchor`` and ``height`` are fractions of the frame, ``base`` is
        # the point of the picture that goes on the anchor.
        "commander_token": (
            versioned(f"/tokens/{SARDAUKAR_COMMANDER_TOKEN_FILENAME}")
            if SARDAUKAR_COMMANDER_TOKEN_FILENAME in token_files
            else None
        ),
        "commander_spot": {
            "anchor": list(COMMANDER_ANCHOR),
            "height": COMMANDER_HEIGHT,
            "base": list(COMMANDER_PICTURE_BASE),
        },
        # Live-state marker coordinates on the scan (Influence, VP, strength,
        # Conflict quadrants, High Council seats), percent of the image.
        "tracks": marker_layout(),
    }
    _add_korean(catalog, korean_images)
    return catalog


def _add_korean(catalog: JsonObject, korean_images: dict[str, str]) -> None:
    """Give entries their Korean name and picture beside the English ones.

    Names come by section and id (``display.names_ko``). Pictures come by
    URL: every ``image`` anywhere in the catalog (a card, a Leader, a
    space, an overlay tile) whose Korean UI picture differs gets
    ``image_ko``, so no section can be left out.
    """

    for section, names in KOREAN_CARD_NAMES.items():
        entries = catalog[section]
        assert isinstance(entries, dict), section
        for entry_id, name in names.items():
            entry = entries[entry_id]
            assert isinstance(entry, dict), entry_id
            entry["name_ko"] = name

    def visit(node: JsonValue) -> None:
        if isinstance(node, dict):
            image = node.get("image")
            if isinstance(image, str) and image in korean_images:
                node["image_ko"] = korean_images[image]
            for value in list(node.values()):
                visit(value)
        elif isinstance(node, list):
            for value in node:
                visit(value)

    visit(catalog)


def _personal_card(
    name: str,
    *,
    cost: int | None,
    persuasion: int,
    swords: int,
    factions: tuple[str, ...],
    agent_icons: tuple[str, ...],
    text: list[str],
    text_ko: list[str],
    image: str | None,
    specimens: int | None = None,
    graft: bool = False,
) -> JsonObject:
    entry: JsonObject = {
        "name": name,
        "cost": cost,
        "persuasion": persuasion,
        "swords": swords,
        "factions": list(factions),
        "agent_icons": list(agent_icons),
        "text": list(text),
        "text_ko": list(text_ko),
        "image": image,
    }
    if specimens is not None:
        # Tleilaxu cards cost specimens [Immortality p. 8].
        entry["specimens"] = specimens
    if graft:
        entry["graft"] = True
    return entry


def _leader_face(
    name: str,
    *,
    ability: str | None,
    signet: str | None,
    face_id: str,
    image_files: dict[tuple[str, str], str],
    layout: JsonValue | None = None,
) -> JsonObject:
    texts = LEADER_FACE_TEXTS[face_id]
    entry: JsonObject = {
        "name": name,
        "ability": ability,
        "signet": signet,
        "ability_text": texts.ability_text,
        "signet_text": texts.signet_text,
        "notes": list(texts.notes),
        "image": _image_url("leader", face_id, image_files),
        # Percent-coordinate boxes for the state a seat's leader popover
        # draws on the card image (display.leader_layout); null for a
        # leader with no printed on-card token/slot state.
        "layout": layout,
    }
    # Korean twin (Step K5, 2026-09-25): a face with a Korean scan carries
    # its transcribed ability/Signet Ring name and text beside the English
    # ones (LOCALIZED_FIELDS in i18n.js already swaps ability/signet by
    # name; core.js's popoverNodes already reads ability_text_ko/
    # signet_text_ko). Absent for reverend_mother_jessica, whose flip face
    # has no Korean scan — the client falls back to English exactly as it
    # does before any _ko field exists.
    texts_ko = LEADER_FACE_TEXTS_KO.get(face_id)
    if texts_ko is not None:
        entry["ability_ko"] = texts_ko.ability_name
        entry["signet_ko"] = texts_ko.signet_name
        entry["ability_text_ko"] = texts_ko.ability_text
        entry["signet_text_ko"] = texts_ko.signet_text
        entry["notes_ko"] = list(texts_ko.notes)
    return entry


def _space(space_id: str, image_files: dict[tuple[str, str], str]) -> JsonObject:
    space = BOARD_SPACES_BY_ID[space_id]
    base_effects = space_option_effects(space_id, choam_module=False)
    base_effects_ko = space_option_effects_ko(space_id, choam_module=False)
    choam_effects = space_option_effects(space_id, choam_module=True)
    choam_effects_ko = space_option_effects_ko(space_id, choam_module=True)
    costs: list[JsonObject] = [
        {"solari": cost.solari, "spice": cost.spice, "water": cost.water}
        for cost in space.cost_options
    ] or [{"solari": 0, "spice": 0, "water": 0}]
    assert len(costs) == space_option_count(space_id)
    options: list[JsonValue] = [
        {"cost": cost, "effect": effect, "effect_ko": effect_ko}
        for cost, effect, effect_ko in zip(
            costs, base_effects, base_effects_ko, strict=True
        )
    ]
    choam_options: list[JsonValue] | None = None
    if choam_effects != base_effects:
        choam_options = [
            {"cost": cost, "effect": effect, "effect_ko": effect_ko}
            for cost, effect, effect_ko in zip(
                costs, choam_effects, choam_effects_ko, strict=True
            )
        ]
    return {
        "name": space.name,
        "agent_icon": space.agent_icon.value,
        "combat": space.combat,
        "maker": space.maker,
        "critical": space.critical,
        "requirement": (
            {
                "faction": space.requirement.faction.value,
                "amount": space.requirement.amount,
            }
            if space.requirement is not None
            else None
        ),
        "dynamic_cost": (
            space.dynamic_cost.value if space.dynamic_cost is not None else None
        ),
        "options": options,
        "choam_options": choam_options,
        "immortality": _immortality_overlay(space_id, costs, base_effects, image_files),
        "notes": list(space_notes(space_id)),
        "notes_ko": list(space_notes_ko(space_id)),
        "box": list(SPACE_BOXES[space_id]),
        "implemented": space_is_implemented(space_id, choam_module=False),
        "choam_implemented": space_is_implemented(space_id, choam_module=True),
        "image": _image_url("location", space_id, image_files),
        # A Leader's own tile (Tuek's Sietch) is on the table only while that
        # Leader plays [Bloodlines p. 12]; the scan has no print for it, so
        # its picture is drawn in its own box, around the frame in "box".
        "required_leader_id": space.required_leader_id,
        "tile_box": (
            list(LEADER_TILE_BOXES[space_id])
            if space.required_leader_id is not None
            else None
        ),
    }


def _immortality_overlay(
    space_id: str,
    costs: list[JsonObject],
    base_effects: tuple[str, ...],
    image_files: dict[tuple[str, str], str],
) -> JsonObject | None:
    """Return what Immortality lays over the space, or ``None``.

    Only the Research Station has an overlay tile: its own effect text (from
    the engine's table for that ruleset), its picture and the box where the
    tile covers the print. No space differs under both CHOAM and
    Immortality, so the client needs no combined variant (a test pins it).
    """

    effects = space_option_effects(space_id, choam_module=False, immortality=True)
    if effects == base_effects:
        return None
    assert space_id == "research_station", space_id
    effects_ko = space_option_effects_ko(space_id, choam_module=False, immortality=True)
    return {
        "options": [
            {"cost": cost, "effect": effect, "effect_ko": effect_ko}
            for cost, effect, effect_ko in zip(costs, effects, effects_ko, strict=True)
        ],
        "image": _image_url("location", RESEARCH_STATION_OVERLAY_IMAGE_ID, image_files),
        "tile_box": list(RESEARCH_STATION_OVERLAY_BOX),
    }


def _conflict_rewards(conflict: ConflictDefinition) -> list[JsonValue] | None:
    texts = conflict_rewards_texts(conflict)
    if texts is None:
        return None
    rewards: list[JsonValue] = list(texts)
    return rewards


def _conflict_rewards_ko(conflict: ConflictDefinition) -> list[JsonValue] | None:
    texts = conflict_rewards_texts_ko(conflict)
    if texts is None:
        return None
    rewards: list[JsonValue] = list(texts)
    return rewards


def card_image_url(path: str) -> str:
    """Return the mounted URL of a card picture; printed names carry spaces etc."""

    return f"/card-images/{quote(path)}"


def _image_url(
    kind: str,
    content_id: str,
    image_files: dict[tuple[str, str], str],
) -> str | None:
    """Look the picture's URL up (``build_catalog`` made them final)."""

    return image_files.get((kind, content_id))
