"""Static display catalog of public printed content for the web UI.

Everything here is printed, table-visible card data taken from the content
manifests — names, costs, icons, and English effect text generated by the
``dune_imperium.display`` package from the same data the engine executes —
so the UI can render informative cards without ever touching hidden state.
The catalog is immutable for a given ruleset build and set of local card
images and safe to cache on the client.

``image_index`` is the server's resolved card-image index — ``(catalog
kind, content_id, "<language>/<path>")`` triples from the private asset
manifest (``display.images``) for files that actually exist — so a
machine without the assets checkout serves the same catalog with every
``image`` field null. ``icon_files`` and ``board_image`` work the same way
for the rulebook icon set (``/icons/...``) and the local board scan
(``/board-image``): the catalog also carries the percent coordinates that
place the live state on that scan (``display.board_layout``).
"""

from functools import cache
from urllib.parse import quote

from dune_imperium.content.uprising.board import BOARD_SPACES_BY_ID
from dune_imperium.content.uprising.conflicts import CONFLICTS, ConflictDefinition
from dune_imperium.content.uprising.contracts import CONTRACTS_BY_ID
from dune_imperium.content.uprising.imperium import IMPERIUM_CARDS_BY_ID
from dune_imperium.content.uprising.intrigue import INTRIGUE_CARDS_BY_ID
from dune_imperium.content.uprising.leaders import LEADERS
from dune_imperium.content.uprising.objectives import OBJECTIVES
from dune_imperium.content.uprising.reserve import RESERVE_STACKS
from dune_imperium.content.uprising.starting_cards import STARTING_CARDS_BY_ID
from dune_imperium.display import (
    LEADER_FACE_TEXTS,
    available_icons,
    conflict_rewards_texts,
    contract_condition_text,
    contract_reward_text,
    intrigue_card_text,
    personal_card_text,
    space_is_implemented,
    space_notes,
    space_option_count,
    space_option_effects,
)
from dune_imperium.display.board_layout import POST_POINTS, SPACE_BOXES
from dune_imperium.server.sessions import JsonObject, JsonValue


@cache
def build_catalog(
    image_index: frozenset[tuple[str, str, str]] = frozenset(),
    icon_files: frozenset[str] = frozenset(),
    board_image: bool = False,
) -> JsonObject:
    """Return every display mapping the browser UI needs, keyed by ID."""

    image_files: dict[tuple[str, str], str] = {
        (kind, content_id): path for kind, content_id, path in image_index
    }
    cards: dict[str, JsonValue] = {}
    for card_id, starter in STARTING_CARDS_BY_ID.items():
        cards[card_id] = _personal_card(
            starter.card.name,
            cost=None,
            persuasion=starter.reveal_persuasion,
            swords=starter.reveal_strength,
            factions=tuple(faction.value for faction in starter.factions),
            agent_icons=tuple(icon.value for icon in starter.agent_icons),
            text=personal_card_text(starter),
            image=_image_url("other", card_id, image_files),
        )
    for stack in RESERVE_STACKS:
        cards[stack.card.card_id] = _personal_card(
            stack.card.name,
            cost=stack.acquisition_cost,
            persuasion=stack.reveal_persuasion,
            swords=stack.reveal_strength,
            factions=(),
            agent_icons=tuple(icon.value for icon in stack.agent_icons),
            text=personal_card_text(stack),
            image=_image_url("other", stack.card.card_id, image_files),
        )
    for card_id, entry in IMPERIUM_CARDS_BY_ID.items():
        cards[card_id] = _personal_card(
            entry.card.name,
            cost=entry.acquisition_cost,
            persuasion=entry.reveal_persuasion,
            swords=entry.reveal_strength,
            factions=tuple(faction.value for faction in entry.factions),
            agent_icons=tuple(icon.value for icon in entry.agent_icons),
            text=personal_card_text(entry),
            image=_image_url("imperium", card_id, image_files),
        )

    intrigue: dict[str, JsonValue] = {}
    for intrigue_id, intrigue_entry in INTRIGUE_CARDS_BY_ID.items():
        timings: list[JsonValue] = [
            timing
            for timing in sorted(
                {option.timing.value for option in intrigue_entry.options}
            )
        ]
        intrigue[intrigue_id] = {
            "name": intrigue_entry.card.name,
            "timings": timings,
            "text": list(intrigue_card_text(intrigue_entry)),
            "image": _image_url("intrigue", intrigue_id, image_files),
        }

    leaders: dict[str, JsonValue] = {}
    for leader in LEADERS:
        leaders[leader.leader_id] = _leader_face(
            leader.name,
            ability=leader.ability_name,
            signet=leader.signet_name,
            face_id=leader.leader_id,
            image_files=image_files,
        )
        if leader.alternate_face_id is not None:
            leaders[leader.alternate_face_id] = _leader_face(
                leader.alternate_face_id.replace("_", " ").title(),
                ability=leader.alternate_ability_name,
                signet=leader.alternate_signet_name,
                face_id=leader.alternate_face_id,
                image_files=image_files,
            )

    return {
        "cards": cards,
        "intrigue": intrigue,
        "contracts": {
            contract_id: {
                "name": definition.card.name,
                "condition": contract_condition_text(definition.condition),
                "reward": contract_reward_text(definition.reward),
                "immediate": definition.completes_immediately,
                "image": _image_url("contract", contract_id, image_files),
            }
            for contract_id, definition in CONTRACTS_BY_ID.items()
        },
        "conflicts": {
            conflict.card.card_id: {
                "name": conflict.card.name,
                "tier": conflict.tier.value,
                "icon": (
                    conflict.battle_icon.value
                    if conflict.battle_icon is not None
                    else None
                ),
                "shield_wall_protected": conflict.shield_wall_protected,
                "rewards": _conflict_rewards(conflict),
                "image": _image_url(
                    "conflict", conflict.card.card_id, image_files
                ),
            }
            for conflict in CONFLICTS
        },
        "leaders": leaders,
        "spaces": {
            space_id: _space(space_id, image_files)
            for space_id in BOARD_SPACES_BY_ID
        },
        "objectives": {
            objective.objective_id: {
                "name": objective.objective_id.replace("_", " ").title(),
                "icon": objective.battle_icon.value,
            }
            for objective in OBJECTIVES
        },
        "posts": {
            post_id: [x, y] for post_id, (x, y) in POST_POINTS.items()
        },
        "icons": {
            name: f"/icons/{filename}"
            for name, filename in available_icons(icon_files).items()
        },
        "board_image": "/board-image" if board_image else None,
    }


def _personal_card(
    name: str,
    *,
    cost: int | None,
    persuasion: int,
    swords: int,
    factions: tuple[str, ...],
    agent_icons: tuple[str, ...],
    text: list[str],
    image: str | None,
) -> JsonObject:
    return {
        "name": name,
        "cost": cost,
        "persuasion": persuasion,
        "swords": swords,
        "factions": list(factions),
        "agent_icons": list(agent_icons),
        "text": list(text),
        "image": image,
    }


def _leader_face(
    name: str,
    *,
    ability: str | None,
    signet: str | None,
    face_id: str,
    image_files: dict[tuple[str, str], str],
) -> JsonObject:
    texts = LEADER_FACE_TEXTS[face_id]
    return {
        "name": name,
        "ability": ability,
        "signet": signet,
        "ability_text": texts.ability_text,
        "signet_text": texts.signet_text,
        "notes": list(texts.notes),
        "image": _image_url("leader", face_id, image_files),
    }


def _space(space_id: str, image_files: dict[tuple[str, str], str]) -> JsonObject:
    space = BOARD_SPACES_BY_ID[space_id]
    base_effects = space_option_effects(space_id, choam_module=False)
    choam_effects = space_option_effects(space_id, choam_module=True)
    costs: list[JsonObject] = [
        {"solari": cost.solari, "spice": cost.spice, "water": cost.water}
        for cost in space.cost_options
    ] or [{"solari": 0, "spice": 0, "water": 0}]
    assert len(costs) == space_option_count(space_id)
    options: list[JsonValue] = [
        {"cost": cost, "effect": effect}
        for cost, effect in zip(costs, base_effects, strict=True)
    ]
    choam_options: list[JsonValue] | None = None
    if choam_effects != base_effects:
        choam_options = [
            {"cost": cost, "effect": effect}
            for cost, effect in zip(costs, choam_effects, strict=True)
        ]
    return {
        "name": space.name,
        "agent_icon": space.agent_icon.value,
        "combat": space.combat,
        "maker": space.maker,
        "critical": space.critical,
        "requirement": (
            {
                "faction": space.requirement.faction.value,
                "amount": space.requirement.amount,
            }
            if space.requirement is not None
            else None
        ),
        "dynamic_cost": (
            space.dynamic_cost.value if space.dynamic_cost is not None else None
        ),
        "options": options,
        "choam_options": choam_options,
        "notes": list(space_notes(space_id)),
        "box": list(SPACE_BOXES[space_id]),
        "implemented": space_is_implemented(space_id, choam_module=False),
        "choam_implemented": space_is_implemented(space_id, choam_module=True),
        "image": _image_url("location", space_id, image_files),
    }


def _conflict_rewards(conflict: ConflictDefinition) -> list[JsonValue] | None:
    texts = conflict_rewards_texts(conflict)
    if texts is None:
        return None
    rewards: list[JsonValue] = list(texts)
    return rewards


def _image_url(
    kind: str,
    content_id: str,
    image_files: dict[tuple[str, str], str],
) -> str | None:
    """Resolve to the mounted file URL; printed names carry spaces etc."""

    path = image_files.get((kind, content_id))
    return f"/card-images/{quote(path)}" if path is not None else None
