"""Emit the app_ai data modules from the extracted Steam app specs.

usage: python app_ai_emit.py [--spec DIR] [--out DIR]

Standard library only. Reads ``constants.json`` (``app_ai_constants.py``) and
``archetypes.json`` (``app_archetypes.py``) from ``--spec`` and writes
``constants.py`` and ``archetypes.py`` into ``--out``
(``src/dune_imperium/agents/app_ai/data`` by default). Both outputs are
deterministic, so re-running on the same build reproduces them byte for byte;
the app_ai package must never be edited by hand where these files are
concerned.

Constant fields keep the app's getter names (``VictoryPointValueEarly``) so a
port reads like the disassembly it was taken from. Every extracted
archetype is kept (app_ai also ports the expansions the app has; ``in_uprising``
flags say what a 4-player Uprising game deals); card text, art and other
display-only attributes are dropped.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

_SPEC_DEFAULT = Path(
    "/Users/cs/Workspace/tabletop-ai/Dune-Imperium-assets/reference/dune-steam-app/"
    "dad97e2021144d45b5b4f022e07bd3b3/analysis/ai/spec"
)
_OUT_DEFAULT = (
    Path(__file__).resolve().parents[2] / "src/dune_imperium/agents/app_ai/data"
)
_DISPLAY_ONLY = frozenset(
    {
        "Image",
        "AgentText",
        "RevealText",
        "GameText",
        "StaticText",
        "LeaderComplexity",
        "LeaderHouse",
        "HagalLeader",
        "Unparseable",
    }
)


def _literal(value: object) -> str:
    """A Python literal for one decoded attribute value (lists become tuples)."""

    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, list):
        inner = ", ".join(_literal(item) for item in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    if isinstance(value, dict):
        items = ", ".join(
            f"{json.dumps(str(key))}: {_literal(item)}"
            for key, item in sorted(value.items())
        )
        return "{" + items + "}"
    if value is None:
        return "None"
    raise TypeError(f"cannot emit {value!r}")


def emit_constants(spec: dict[str, object], build: str, version: str) -> str:
    getters = spec["getters"]
    assert isinstance(getters, list)
    lines = [
        '"""The app AI constant tables (``worm.canis.ai.AIConstantsRef`` and',
        "its Medium/Easy subclasses), one field per getter in vtable order.",
        "",
        f"Generated by ``scripts/dwgr/app_ai_emit.py`` from app {version}",
        f"(build {build}).",
        "Do not edit by hand; re-run the extractor and the emitter instead.",
        "Field names are the app's getter names without ``get_``.",
        '"""',
        "",
        "from dataclasses import dataclass",
        "from types import MappingProxyType",
        "from typing import Final",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class AIConstants:",
        '    """Every AI tuning constant of one difficulty table."""',
        "",
    ]
    for getter in getters:
        kind = "int" if getter["type"] == "int" else "float"
        lines.append(f"    {getter['name']}: {kind}")
    for level, key in (("HARD", "hard"), ("MEDIUM", "medium"), ("EASY", "easy")):
        lines += ["", "", f"{level}: Final = AIConstants("]
        for getter in getters:
            value = getter[key]
            if getter["type"] == "int":
                rendered = str(int(value))
            else:
                rendered = repr(float(value))
            lines.append(f"    {getter['name']}={rendered},")
        lines.append(")")
    overridden = [g["name"] for g in getters if g.get("overridden_by")]
    lines += [
        "",
        "# AILevel -> table, as ``worm.canis.ai.AIConstants..cctor`` registers them",
        "# (level 3 is registered as Hard but nothing in the app sets it).",
        "TABLES: Final = MappingProxyType({0: EASY, 1: MEDIUM, 2: HARD, 3: HARD})",
        "",
        "# The getters AIMediumConstantsRef and AIEasyConstantsRef override.",
        "OVERRIDDEN: Final = (",
        *[f"    {json.dumps(name)}," for name in overridden],
        ")",
        "",
    ]
    return "\n".join(lines)


def _kept(record: dict[str, object]) -> bool:
    """Every extracted archetype: app_ai also ports the expansions the app has
    (Immortality, Epic's Control the Spice, the promos) and reads the Rise of Ix
    tech tiles' data for the Bloodlines Tech Module rule."""

    return True


def emit_archetypes(records: list[dict[str, object]], build: str, version: str) -> str:
    kept = sorted((r for r in records if _kept(r)), key=lambda r: str(r["short"]))
    lines = [
        '"""Every app archetype the extractor reads (all sets, Hagal and',
        "mode-only content excluded): every attribute the AI can read, and the",
        "ability list. ``in_uprising``/``in_uprising_choam`` say whether a 4-player",
        "Uprising game deals it without/with the CHOAM module.",
        "",
        f"Generated by ``scripts/dwgr/app_ai_emit.py`` from app {version}",
        f"(build {build}).",
        "Do not edit by hand. Keys are the app's namespace-qualified short names,",
        "e.g. ``ImperiumArchetypes.Uprising.CapturedMentat``.",
        '"""',
        "",
        "# ruff: noqa: E501  (generated data: ability class names do not wrap)",
        "",
        "from collections.abc import Mapping",
        "from dataclasses import dataclass",
        "from types import MappingProxyType",
        "from typing import Final",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class Archetype:",
        '    """One app archetype: identity, game membership and attributes."""',
        "",
        "    short: str",
        "    kind: str",
        "    title: str | None",
        "    in_uprising: bool",
        "    in_uprising_choam: bool",
        "    attributes: Mapping[str, object]",
        "",
        "",
        "ARCHETYPES: Final[Mapping[str, Archetype]] = MappingProxyType(",
        "    {",
    ]
    for record in kept:
        in_game = record["in_game"]
        assert isinstance(in_game, dict)
        attributes = record["attributes"]
        assert isinstance(attributes, dict)
        lines.append(f"        {json.dumps(record['short'])}: Archetype(")
        lines.append(f"            short={json.dumps(record['short'])},")
        lines.append(f"            kind={json.dumps(record['kind'])},")
        lines.append(f"            title={_literal(record['title'])},")
        lines.append(f"            in_uprising={bool(in_game.get('uprising'))},")
        lines.append(
            f"            in_uprising_choam={bool(in_game.get('uprising_choam'))},"
        )
        lines.append("            attributes=MappingProxyType(")
        lines.append("                {")
        for key in sorted(attributes):
            if key in _DISPLAY_ONLY:
                continue
            lines.append(
                f"                    {json.dumps(key)}: {_literal(attributes[key])},"
            )
        lines.append("                }")
        lines.append("            ),")
        lines.append("        ),")
    lines += ["    }", ")", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--spec", type=Path, default=_SPEC_DEFAULT)
    parser.add_argument("--out", type=Path, default=_OUT_DEFAULT)
    args = parser.parse_args()
    constants = json.loads((args.spec / "constants.json").read_text())
    archetypes = json.loads((args.spec / "archetypes.json").read_text())
    build = str(constants["build_guid"])
    version = str(constants["app_version"])
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "constants.py").write_text(emit_constants(constants, build, version))
    (args.out / "archetypes.py").write_text(emit_archetypes(archetypes, build, version))
    print(f"wrote {args.out / 'constants.py'} and {args.out / 'archetypes.py'}")


if __name__ == "__main__":
    main()
